INSERT INTO type (name) VALUES
    ('Naissance'),
    ('Décès'),
    ('Mariage'),
    ('Couronnement'),
    ('Règne'),
    ('Guerre'),
    ('Bataille'),
    ('Révolution'),
    ('Révolte'),
    ('Coup d''État'),
    ('Indépendance'),
    ('Conquête'),
    ('Invasion'),
    ('Traité'),
    ('Alliance'),
    ('Fondation'),
    ('Création'),
    ('Découverte'),
    ('Invention'),
    ('Catastrophe'),
    ('Épidémie'),
    ('Événement politique'),
    ('Événement religieux'),
    ('Événement culturel'),
    ('Événement économique');