-- AFRIQUE DU SUD --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Développement des sociétés khoïsan', 'developpement-societes-khoisan-ZA', '00001-01-01', '00299-12-31', 'Les populations san et khoïkhoï développent des sociétés de chasseurs-cueilleurs et d’éleveurs dans différentes régions de l’actuelle Afrique du Sud.', NULL, 17),
('Installation de populations bantouphones', 'installation-populations-bantouphones-ZA', '00300-01-01', '00300-12-31', 'Des populations bantouphones commencent à s’installer dans le sud de l’Afrique, notamment dans les régions orientales de l’actuelle Afrique du Sud.', NULL, 17),
('Développement du royaume de Mapungubwe', 'royaume-mapungubwe-ZA', '01075-01-01', '01220-12-31', 'Mapungubwe devient un centre politique et commercial majeur, notamment grâce au commerce de l’or et de l’ivoire avec des réseaux de l’océan Indien.', NULL, 17),
('Bartolomeu Dias atteint le cap de Bonne-Espérance', 'dias-cap-bonne-esperance-ZA', '01488-01-01', '01488-12-31', 'Le navigateur portugais Bartolomeu Dias franchit l’extrémité méridionale de l’Afrique lors de son expédition vers l’océan Indien.', NULL, 18),
('Vasco de Gama atteint la côte du Natal', 'vasco-de-gama-cote-natal-ZA', '01497-12-01', '01497-12-31', 'L’expédition de Vasco de Gama atteint la côte orientale de l’Afrique australe lors de son voyage vers l’Inde.', NULL, 18),
('Fondation de la colonie du Cap', 'fondation-colonie-cap-ZA', '01652-04-06', '01652-04-06', 'Jan van Riebeeck établit pour la Compagnie néerlandaise des Indes orientales une station de ravitaillement à Table Bay.', NULL, 16),
('Première guerre khoïkhoï-néerlandaise', 'premiere-guerre-khoikhoi-neerlandaise-ZA', '01659-01-01', '01659-12-31', 'Le premier conflit majeur oppose les populations khoïkhoï aux colons néerlandais du Cap.', NULL, 6),
('Début de l’importation d’esclaves au Cap', 'debut-esclavage-cap-ZA', '01658-01-01', '01658-12-31', 'La colonie du Cap commence à importer des personnes réduites en esclavage depuis Madagascar et l’Asie du Sud-Est.', NULL, 25),
('Arrivée des huguenots français au Cap', 'arrivee-huguenots-francais-cap-ZA', '01688-01-01', '01690-12-31', 'Des réfugiés huguenots français s’installent dans la colonie du Cap et contribuent notamment au développement de la viticulture.', NULL, 17),
('Établissement officiel de la colonie du Cap', 'etablissement-officiel-colonie-cap-ZA', '01691-01-01', '01691-12-31', 'La colonie du Cap est officiellement constituée comme colonie néerlandaise de la Compagnie des Indes orientales.', NULL, 17),
('Première occupation britannique du Cap', 'premiere-occupation-britannique-cap-ZA', '01795-09-01', '01795-09-01', 'Les forces britanniques occupent la colonie du Cap dans le contexte des guerres révolutionnaires européennes.', NULL, 13),
('Restitution du Cap à la République batave', 'restitution-cap-republique-batave-ZA', '01803-01-01', '01803-12-31', 'Le traité d’Amiens entraîne la restitution de la colonie du Cap à la République batave.', NULL, 14),
('Seconde occupation britannique du Cap', 'seconde-occupation-britannique-cap-ZA', '01806-01-08', '01806-01-08', 'Les Britanniques reprennent le contrôle de la colonie du Cap lors des guerres napoléoniennes.', NULL, 13),
('Abolition de la traite britannique des esclaves', 'abolition-traite-esclaves-britannique-ZA', '01807-03-25', '01807-03-25', 'Le Parlement britannique adopte l’abolition de la traite des esclaves dans l’Empire britannique, avec des conséquences pour la colonie du Cap.', NULL, 22),
('Cession définitive de la colonie du Cap à la Grande-Bretagne', 'cession-colonie-cap-grande-bretagne-ZA', '01814-01-01', '01814-12-31', 'Les Pays-Bas cèdent définitivement la colonie du Cap à la Grande-Bretagne.', NULL, 14),
('Création et expansion du royaume zoulou', 'creation-royaume-zoulou-ZA', '01816-01-01', '01828-12-31', 'Shaka établit et développe un puissant royaume zoulou en Afrique australe.', NULL, 16),
('Bataille de Blood River', 'bataille-blood-river-ZA', '01838-12-16', '01838-12-16', 'Les forces boers remportent une victoire contre l’armée zouloue lors de la bataille de Blood River.', NULL, 7),
('Fondation de la république de Natalia', 'fondation-republique-natalia-ZA', '01839-01-01', '01839-12-31', 'Des Voortrekkers établissent la république de Natalia dans la région de Natal.', NULL, 16),
('Convention de Sand River', 'convention-sand-river-ZA', '01852-01-17', '01852-01-17', 'La Grande-Bretagne reconnaît l’indépendance du territoire boer situé au nord du Vaal, qui devient la République sud-africaine du Transvaal.', NULL, 14),
('Fondation de l’État libre d’Orange', 'fondation-etat-libre-orange-ZA', '01854-02-23', '01854-02-23', 'La Convention de Bloemfontein reconnaît l’indépendance de l’État libre d’Orange.', NULL, 16),
('Crise du bétail xhosa', 'crise-betail-xhosa-ZA', '01856-01-01', '01857-12-31', 'Le mouvement prophétique de Nongqawuse entraîne l’abattage massif du bétail xhosa et une grave crise alimentaire et sociale.', NULL, 20),
('Découverte des diamants de Kimberley', 'decouverte-diamants-kimberley-ZA', '01867-01-01', '01867-12-31', 'La découverte de diamants dans la région de Kimberley déclenche une importante transformation économique et démographique.', NULL, 18),
('Guerre anglo-zouloue', 'guerre-anglo-zouloue-ZA', '01879-01-22', '01879-07-01', 'La guerre oppose l’Empire britannique au royaume zoulou et aboutit à la défaite du royaume zoulou.', NULL, 6),
('Première guerre des Boers', 'premiere-guerre-boers-ZA', '01880-12-16', '01881-03-23', 'Les Boers du Transvaal se soulèvent contre l’autorité britannique lors de la première guerre des Boers.', NULL, 6),
('Ruée vers l’or du Witwatersrand', 'ruee-or-witwatersrand-ZA', '01886-01-01', '01886-12-31', 'La découverte de vastes gisements d’or au Witwatersrand transforme profondément l’économie et la démographie de la région.', NULL, 18),
('Fondation de Johannesburg', 'fondation-johannesburg-ZA', '01886-01-01', '01886-12-31', 'Johannesburg se développe rapidement à la suite de la découverte de l’or dans le Witwatersrand.', NULL, 16),
('Seconde guerre des Boers', 'seconde-guerre-boers-ZA', '01899-10-11', '01902-05-31', 'La Grande-Bretagne affronte les républiques boers du Transvaal et de l’État libre d’Orange lors de la seconde guerre des Boers.', NULL, 6),
('Traité de Vereeniging', 'traite-vereeniging-ZA', '01902-05-31', '01902-05-31', 'Le traité de Vereeniging met fin à la seconde guerre des Boers et place les anciennes républiques boers sous souveraineté britannique.', NULL, 14),
('Création de l’Union sud-africaine', 'creation-union-sud-africaine-ZA', '01910-05-31', '01910-05-31', 'Les colonies du Cap, du Natal, du Transvaal et de l’État libre d’Orange sont réunies pour former l’Union sud-africaine.', NULL, 17),
('Fondation du Congrès national africain', 'fondation-congres-national-africain-ZA', '01912-01-08', '01912-01-08', 'Le South African Native National Congress, devenu l’African National Congress, est fondé pour défendre les droits politiques de la population noire.', NULL, 17),
('Natives Land Act', 'natives-land-act-ZA', '01913-06-19', '01913-06-19', 'Le Natives Land Act limite fortement l’accès des populations africaines à la propriété foncière hors des réserves désignées.', NULL, 22),
('Droit de vote des femmes blanches', 'droit-vote-femmes-blanches-ZA', '01930-01-01', '01930-12-31', 'L’Union sud-africaine accorde le droit de vote aux femmes blanches, sans instaurer un suffrage universel.', NULL, 22),
('Statut d’indépendance de l’Union sud-africaine', 'statut-independance-union-sud-africaine-ZA', '01931-12-11', '01931-12-11', 'Le Statute of Westminster reconnaît une large autonomie législative aux dominions, dont l’Union sud-africaine.', NULL, 11),
('Victoire du Parti national', 'victoire-parti-national-ZA', '01948-05-26', '01948-05-26', 'Le Parti national remporte les élections générales et commence à mettre en place l’apartheid comme politique officielle de l’État.', NULL, 22),
('Adoption du Group Areas Act', 'adoption-group-areas-act-ZA', '01950-04-27', '01950-04-27', 'Le Group Areas Act organise la séparation résidentielle des populations selon des catégories raciales.', NULL, 22),
('Campagne de défiance', 'campagne-defiance-ZA', '01952-06-26', '01952-12-31', 'Une campagne nationale de désobéissance civile contre les lois de ségrégation est lancée par des organisations opposées à l’apartheid.', NULL, 9),
('Adoption de la Charte de la liberté', 'charte-liberte-ZA', '01955-06-26', '01955-06-26', 'Le Congrès du peuple adopte à Kliptown la Charte de la liberté, qui énonce des principes pour une Afrique du Sud démocratique.', NULL, 22),
('Massacre de Sharpeville', 'massacre-sharpeville-ZA', '01960-03-21', '01960-03-21', 'La police ouvre le feu sur des manifestants à Sharpeville lors d’une mobilisation contre les lois sur les laissez-passer.', NULL, 22),
('Proclamation de la République sud-africaine', 'proclamation-republique-sud-africaine-ZA', '01961-05-31', '01961-05-31', 'L’Union sud-africaine devient la République d’Afrique du Sud à la suite du référendum constitutionnel de 1960.', NULL, 22),
('Procès de Rivonia', 'proces-rivonia-ZA', '01963-10-09', '01964-06-11', 'Le procès de Rivonia conduit à la condamnation à la prison à vie de plusieurs dirigeants de la lutte contre l’apartheid, dont Nelson Mandela.', NULL, 22),
('Première transplantation cardiaque humaine', 'premiere-transplantation-cardiaque-ZA', '01967-12-03', '01967-12-03', 'Christiaan Barnard réalise au Cap la première transplantation cardiaque humaine réussie.', NULL, 19),
('Soulèvement de Soweto', 'soulevement-soweto-ZA', '01976-06-16', '01976-12-31', 'Des manifestations étudiantes à Soweto contre la politique linguistique de l’enseignement sont réprimées violemment et déclenchent une mobilisation nationale.', NULL, 9),
('Fondation du United Democratic Front', 'fondation-united-democratic-front-ZA', '01983-08-20', '01983-08-20', 'Le United Democratic Front est créé pour coordonner de nombreuses organisations opposées à l’apartheid.', NULL, 17),
('État d’urgence de 1985', 'etat-urgence-1985-ZA', '01985-07-20', '01985-12-31', 'Le gouvernement sud-africain proclame un état d’urgence dans plusieurs régions face à l’intensification des mobilisations et des violences politiques.', NULL, 22),
('Libération de Nelson Mandela et légalisation de l’ANC', 'liberation-mandela-legalisation-anc-ZA', '01990-02-11', '01990-02-11', 'Nelson Mandela est libéré après vingt-sept années de détention et le gouvernement annonce la levée de l’interdiction de plusieurs organisations politiques.', NULL, 22),
('Adoption de la Constitution intérimaire', 'adoption-constitution-interimaire-ZA', '01993-11-18', '01993-12-22', 'Les négociations politiques aboutissent à une Constitution intérimaire qui prépare la transition vers un régime démocratique.', NULL, 22),
('Premières élections démocratiques non raciales', 'premieres-elections-democratiques-ZA', '01994-04-27', '01994-04-29', 'L’Afrique du Sud organise ses premières élections nationales au suffrage universel sans distinction raciale.', NULL, 22),
('Élection de Nelson Mandela à la présidence', 'election-nelson-mandela-president-ZA', '01994-05-09', '01994-05-09', 'Le Parlement élit Nelson Mandela président de la République d’Afrique du Sud.', NULL, 22),
('Création de la Commission vérité et réconciliation', 'creation-commission-verite-reconciliation-ZA', '01995-01-01', '01995-12-31', 'La Commission vérité et réconciliation est mise en place pour enquêter sur les violations des droits humains commises pendant la période de l’apartheid.', NULL, 22),
('Adoption de la Constitution de 1996', 'constitution-afrique-du-sud-1996-ZA', '01996-12-04', '01996-12-10', 'La nouvelle Constitution est approuvée par la Cour constitutionnelle puis signée par Nelson Mandela, établissant le cadre constitutionnel de la nouvelle Afrique du Sud.', NULL, 22);


-- ALGERIE --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES

('Révolte de Tacfarinas', 'revolte-tacfarinas-DZ', '00017-01-01', '00024-12-31', 'Tacfarinas dirige une longue révolte contre la domination romaine en Afrique du Nord.', NULL, 9),
('Donatisme en Afrique du Nord', 'donatisme-afrique-du-nord-DZ', '00311-01-01', '00411-12-31', 'Le mouvement donatiste se développe en Afrique du Nord et provoque un important conflit religieux au sein du christianisme africain.', NULL, 23),
('Invasion vandale de l’Afrique du Nord', 'invasion-vandale-afrique-du-nord-DZ', '00429-01-01', '00439-12-31', 'Les Vandales envahissent l’Afrique du Nord et établissent un royaume dont le centre se trouve à Carthage.', NULL, 13),
('Conquête byzantine de l’Afrique du Nord', 'conquete-byzantine-afrique-du-nord-DZ', '00533-01-01', '00534-12-31', 'Les armées de Justinien reconquièrent l’Afrique du Nord sur les Vandales et rétablissent l’autorité byzantine.', NULL, 12),
('Conquête arabe du Maghreb central', 'conquete-arabe-maghreb-central-DZ', '00670-01-01', '00700-12-31', 'Les armées arabes conquièrent progressivement le Maghreb central et introduisent durablement l’islam dans la région.', NULL, 12),
('Révolte berbère contre les Omeyyades', 'revolte-berbere-omeyyades-DZ', '00739-01-01', '00740-12-31', 'La grande révolte berbère remet en cause l’autorité omeyyade au Maghreb et entraîne la fragmentation politique de la région.', NULL, 9),
('Fondation de Tahert par les Rustumides', 'fondation-tahert-rustumides-DZ', '00761-01-01', '00761-12-31', 'Tahert devient la capitale de l’imamat rustumide et un important centre politique, commercial et intellectuel du Maghreb.', NULL, 16),
('Fondation de la dynastie ziride', 'fondation-dynastie-ziride-DZ', '00972-01-01', '00972-12-31', 'Bologhine ibn Ziri établit la dynastie ziride en Ifriqiya et développe plusieurs centres urbains du Maghreb central.', NULL, 16),
('Fondation d’Alger par les Zirides', 'fondation-alger-zirides-DZ', '00960-01-01', '00960-12-31', 'Alger, héritière de l’ancienne Icosium, se développe sous les Zirides comme un important centre urbain et portuaire.', NULL, 16),
('Fondation de la Qal’a des Beni Hammad', 'fondation-qalaa-beni-hammad-DZ', '01007-01-01', '01008-12-31', 'Les Hammadides fondent la Qal’a des Beni Hammad, qui devient un important centre politique et culturel du Maghreb central.', NULL, 16),
('Invasion hilalienne du Maghreb', 'invasion-hilalienne-maghreb-DZ', '01051-01-01', '01051-12-31', 'L’arrivée des tribus hilaliennes au Maghreb bouleverse durablement les équilibres politiques, économiques et linguistiques de la région.', NULL, 13),
('Prise de Tlemcen par les Almoravides', 'prise-tlemcen-almoravides-DZ', '01082-01-01', '01082-12-31', 'Les Almoravides prennent Tlemcen et renforcent leur contrôle sur le Maghreb central.', NULL, 12),
('Fondation de la dynastie almohade', 'fondation-dynastie-almohade-DZ', '01126-01-01', '01126-12-31', 'Le mouvement almohade se développe dans le Maghreb et finit par établir un vaste empire nord-africain.', NULL, 16),
('Prise de Bejaia par les Hafsides', 'prise-bejaia-hafsides-DZ', '01229-01-01', '01229-12-31', 'Bejaia devient un centre majeur de l’État hafside et joue un rôle important dans le commerce méditerranéen.', NULL, 12),
('Fondation du royaume zianide de Tlemcen', 'fondation-royaume-zianide-tlemcen-DZ', '01236-01-01', '01236-12-31', 'Yaghmoracen Ibn Ziane fonde le royaume zianide centré sur Tlemcen, qui domine une partie du Maghreb central.', NULL, 16),
('Prise d’Oran par les Espagnols', 'prise-oran-espagnols-DZ', '01509-05-17', '01509-05-17', 'Les forces espagnoles prennent Oran et établissent une importante position sur la côte algérienne.', NULL, 13),
('Prise de Bejaia par les Espagnols', 'prise-bejaia-espagnols-DZ', '01510-01-01', '01510-01-01', 'Les forces espagnoles prennent Bejaia et établissent une présence militaire sur la côte algérienne.', NULL, 13),
('Arrivée d’Arudj Barberousse à Alger', 'arrivee-arudj-barberousse-alger-DZ', '01516-01-01', '01516-12-31', 'Arudj Barberousse arrive à Alger et s’allie avec les autorités locales pour combattre la présence espagnole.', NULL, 17),
('Prise d’Alger par Khayr ad-Din Barberousse', 'prise-alger-khayr-ad-din-DZ', '01529-01-01', '01529-12-31', 'Khayr ad-Din Barberousse reprend le Penon d’Alger et consolide l’intégration d’Alger à l’Empire ottoman.', NULL, 12),
('Bataille de la baie d’Alger', 'bataille-baie-alger-DZ', '01541-10-23', '01541-10-27', 'L’expédition de Charles Quint contre Alger échoue face aux défenseurs de la Régence et aux conditions météorologiques.', NULL, 7),
('Bombardement d’Alger par la flotte anglo-néerlandaise', 'bombardement-alger-anglo-neerlandais-DZ', '01816-08-27', '01816-08-28', 'Une flotte anglo-néerlandaise bombarde Alger et contraint la Régence à accepter des engagements concernant la course et l’esclavage.', NULL, 20),
('Débarquement français à Sidi-Ferruch', 'debarquement-francais-sidi-ferruch-DZ', '01830-06-14', '01830-06-14', 'Les forces françaises débarquent à Sidi-Ferruch au début de l’expédition militaire contre la Régence d’Alger.', NULL, 13),
('Prise d’Alger par les Français', 'prise-alger-francais-DZ', '01830-07-05', '01830-07-05', 'Les forces françaises prennent Alger et mettent fin au pouvoir de la Régence d’Alger.', NULL, 12),
('Résistance d’Abdelkader contre la conquête française', 'resistance-abdelkader-conquete-francaise-DZ', '01832-01-01', '01847-12-23', 'L’émir Abdelkader organise un État et dirige une longue résistance contre la conquête française de l’Algérie.', NULL, 6),
('Bataille de la Macta', 'bataille-macta-DZ', '01835-06-28', '01835-06-28', 'Les forces de l’émir Abdelkader infligent une importante défaite aux troupes françaises du général Trézel près de la Macta.', NULL, 7),
('Prise de Mascara par les Français', 'prise-mascara-francais-DZ', '01835-12-06', '01835-12-06', 'Les forces françaises prennent Mascara, capitale de l’émirat d’Abdelkader, lors de la campagne menée en Oranie.', NULL, 12),
('Traité de la Tafna', 'traite-tafna-DZ', '01837-05-30', '01837-05-30', 'Le traité de la Tafna établit temporairement un partage territorial entre les forces françaises et l’émirat d’Abdelkader.', NULL, 14),
('Prise de Constantine', 'prise-constantine-francais-DZ', '01837-10-13', '01837-10-13', 'Les forces françaises prennent Constantine après plusieurs tentatives et consolident leur présence dans l’est de l’Algérie.', NULL, 12),
('Reddition d’Abdelkader', 'reddition-abdelkader-DZ', '01847-12-23', '01847-12-23', 'Abdelkader se rend aux autorités françaises, marquant la fin de la principale résistance organisée à la conquête française.', NULL, 14),
('Insurrection de Mokrani', 'insurrection-mokrani-DZ', '01871-03-16', '01872-01-01', 'L’insurrection dirigée par le cheikh Mokrani constitue l’un des plus importants soulèvements contre l’autorité coloniale française au XIXe siècle.', NULL, 9),
('Création du Parti du peuple algérien', 'creation-parti-peuple-algerien-DZ', '01937-03-11', '01937-03-11', 'Messali Hadj fonde le Parti du peuple algérien, qui devient une organisation majeure du mouvement nationaliste algérien.', NULL, 17),
('Massacre de Sétif, Guelma et Kherrata', 'massacre-setif-guelma-kherrata-DZ', '01945-05-08', '01945-05-08', 'Des manifestations nationalistes sont suivies d’une répression meurtrière dans plusieurs régions de l’est algérien.', NULL, 20),
('Création du Front de libération nationale', 'creation-front-liberation-nationale-DZ', '01954-10-10', '01954-10-10', 'Le Front de libération nationale est créé afin de coordonner la lutte pour l’indépendance de l’Algérie.', NULL, 17),
('Début de la guerre d’indépendance algérienne', 'debut-guerre-independance-algerienne-DZ', '01954-11-01', '01954-11-01', 'Le FLN déclenche une série d’attaques qui marque le début de la guerre d’indépendance algérienne.', NULL, 6),
('Congrès de la Soummam', 'congres-soummam-DZ', '01956-08-20', '01956-08-20', 'Le Congrès de la Soummam réorganise les structures politiques et militaires du mouvement indépendantiste algérien.', NULL, 22),
('Bataille d’Alger', 'bataille-alger-DZ', '01956-09-30', '01957-10-01', 'La bataille d’Alger oppose les réseaux du FLN aux forces françaises et devient un épisode majeur de la guerre d’indépendance.', NULL, 7),
('Création du Gouvernement provisoire de la République algérienne', 'creation-gouvernement-provisoire-republique-algerienne-DZ', '01958-09-19', '01958-09-19', 'Le Gouvernement provisoire de la République algérienne est créé au Caire pour représenter le mouvement indépendantiste.', NULL, 17),
('Accords d’Évian', 'accords-evian-DZ', '01962-03-18', '01962-03-18', 'Les accords d’Évian mettent fin aux hostilités entre la France et le Gouvernement provisoire de la République algérienne.', NULL, 14),
('Référendum sur l’indépendance de l’Algérie', 'referendum-independance-algerie-DZ', '01962-07-01', '01962-07-01', 'La population algérienne se prononce massivement en faveur de l’indépendance lors du référendum prévu par les accords d’Évian.', NULL, 22),
('Indépendance de l’Algérie', 'independance-algerie-DZ', '01962-07-05', '01962-07-05', 'L’Algérie proclame son indépendance après 132 années de domination coloniale française.', NULL, 11),
('Proclamation de la République algérienne démocratique et populaire', 'proclamation-republique-algerienne-DZ', '01962-09-25', '01962-09-25', 'L’Assemblée constituante proclame la République algérienne démocratique et populaire.', NULL, 22),
('Coup d’État de Houari Boumédiène', 'coup-etat-boumediene-DZ', '01965-06-19', '01965-06-19', 'Houari Boumédiène renverse le président Ahmed Ben Bella lors d’un coup d’État militaire.', NULL, 10),
('Nationalisation des hydrocarbures', 'nationalisation-hydrocarbures-algerie-DZ', '01971-02-24', '01971-02-24', 'L’Algérie nationalise une grande partie des intérêts étrangers dans son secteur des hydrocarbures.', NULL, 25),
('Adoption de la Charte nationale', 'adoption-charte-nationale-algerie-DZ', '01976-06-27', '01976-06-27', 'Un référendum approuve la Charte nationale qui définit les grandes orientations politiques et économiques de l’État algérien.', NULL, 22),
('Émeutes d’Octobre 1988', 'emeutes-octobre-1988-DZ', '01988-10-05', '01988-10-10', 'Des manifestations et émeutes éclatent dans plusieurs villes algériennes et entraînent une profonde crise politique.', NULL, 9),
('Adoption de la Constitution de 1989', 'constitution-algerienne-1989-DZ', '01989-02-23', '01989-02-23', 'Une nouvelle Constitution introduit le multipartisme et modifie profondément le système politique algérien.', NULL, 22),
('Début de la décennie noire', 'debut-decennie-noire-DZ', '01991-12-26', '01991-12-26', 'L’interruption du processus électoral et l’affrontement entre groupes armés et autorités marquent le début d’une longue période de violence politique.', NULL, 6),
('Adoption de la Constitution de 1996', 'constitution-algerienne-1996-DZ', '01996-11-28', '01996-11-28', 'Une nouvelle Constitution réorganise les institutions algériennes dans le contexte de la décennie de violence politique.', NULL, 22),
('Charte pour la paix et la réconciliation nationale', 'charte-paix-reconciliation-nationale-DZ', '02005-09-29', '02005-09-29', 'Un référendum approuve la Charte pour la paix et la réconciliation nationale destinée à favoriser la sortie de la décennie de violence.', NULL, 22),
('Manifestations algériennes de 2019', 'manifestations-algeriennes-2019-DZ', '02019-02-22', '02019-12-31', 'Un vaste mouvement de manifestations, appelé Hirak, conduit au retrait de la candidature d’Abdelaziz Bouteflika et à une transition politique.', NULL, 9);


-- ANGOLA --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Développement du royaume du Kongo', 'developpement-royaume-kongo-AO', '01390-01-01', '01400-12-31', 'Le royaume du Kongo se développe autour du bassin inférieur du Congo et exerce une influence importante sur le nord de l’actuelle Angola.', NULL, 16),
('Établissement des premiers contacts portugais avec le Kongo', 'premiers-contacts-portugais-kongo-AO', '01483-01-01', '01483-12-31', 'Les navigateurs portugais établissent des contacts avec le royaume du Kongo lors des expéditions de Diogo Cão sur la côte africaine.', NULL, 18),
('Fondation de Luanda', 'fondation-luanda-AO', '01576-01-25', '01576-01-25', 'Paulo Dias de Novais fonde Luanda comme base de l’expansion portugaise dans la région.', NULL, 16),
('Résistance de la reine Njinga', 'resistance-reine-njinga-AO', '01620-01-01', '01663-12-31', 'Njinga Mbandi dirige les royaumes de Ndongo et Matamba et organise une longue résistance à l’expansion portugaise.', NULL, 9),
('Occupation néerlandaise de Luanda', 'occupation-neerlandaise-luanda-AO', '01641-08-01', '01641-08-01', 'Les forces néerlandaises de la Compagnie néerlandaise des Indes occidentales prennent Luanda et chassent temporairement les Portugais.', NULL, 13),
('Reprise de Luanda par les Portugais', 'reprise-luanda-portugais-AO', '01648-08-15', '01648-08-15', 'Les forces portugaises commandées par Salvador Correia de Sá reprennent Luanda aux Néerlandais.', NULL, 12),
('Expansion de la traite esclavagiste depuis l’Angola', 'expansion-traite-esclavagiste-angola-AO', '01700-01-01', '01800-12-31', 'Luanda et Benguela deviennent des centres majeurs de la traite atlantique reliant l’Angola aux Amériques.', NULL, 25),
('Fondation de Benguela', 'fondation-benguela-AO', '01617-05-17', '01617-05-17', 'Les Portugais fondent Benguela sur la côte afin de renforcer leur implantation et leurs réseaux commerciaux dans le sud de l’Angola.', NULL, 16),
('Abolition officielle de la traite des esclaves dans les territoires portugais', 'abolition-traite-esclaves-portugais-AO', '01836-02-10', '01836-02-10', 'Le Portugal interdit officiellement la traite des esclaves dans ses territoires, même si le commerce clandestin se poursuit pendant plusieurs années.', NULL, 22),
('Conférence de Berlin et reconnaissance des revendications portugaises', 'conference-berlin-revendications-portugaises-AO', '01884-11-15', '01885-02-26', 'La conférence de Berlin accélère le partage colonial de l’Afrique et contribue à la reconnaissance internationale des revendications portugaises en Angola.', NULL, 22),
('Délimitation des frontières de l’Angola portugais', 'delimitation-frontieres-angola-portugais-AO', '01890-01-01', '01901-12-31', 'Les accords entre puissances européennes contribuent à fixer progressivement les frontières internationales de l’Angola colonial.', NULL, 14),
('Révolte de Baixa de Cassanje', 'revolte-baixa-cassanje-AO', '01961-01-03', '01961-01-31', 'Une révolte des travailleurs agricoles de la région de Baixa de Cassanje contre les conditions imposées par le système colonial est durement réprimée.', NULL, 9),
('Début de la guerre d’indépendance angolaise', 'debut-guerre-independance-angola-AO', '01961-02-04', '01961-02-04', 'Des attaques contre des installations coloniales à Luanda marquent le début de la guerre d’indépendance angolaise.', NULL, 6),
('Création de l’UNITA', 'creation-unita-AO', '01966-03-13', '01966-03-13', 'Jonas Savimbi fonde l’Union nationale pour l’indépendance totale de l’Angola, qui devient l’un des principaux mouvements nationalistes angolais.', NULL, 17),
('Révolution des Œillets au Portugal', 'revolution-oeillets-portugal-angola-AO', '01974-04-25', '01974-04-25', 'Le renversement du régime portugais ouvre la voie à la fin de la guerre coloniale et aux négociations sur l’indépendance de l’Angola.', NULL, 8),
('Accords d’Alvor', 'accords-alvor-AO', '01975-01-15', '01975-01-15', 'Le Portugal, le MPLA, la FNLA et l’UNITA concluent les accords d’Alvor qui prévoient un gouvernement de transition et l’indépendance de l’Angola.', NULL, 14),
('Indépendance de l’Angola', 'independance-angola-AO', '01975-11-11', '01975-11-11', 'L’Angola proclame son indépendance du Portugal et Agostinho Neto devient le premier président du nouvel État.', NULL, 11),
('Début de la guerre civile angolaise', 'debut-guerre-civile-angola-AO', '01975-11-11', '02002-04-04', 'Après l’indépendance, le conflit entre le MPLA, l’UNITA et la FNLA se transforme en une longue guerre civile, impliquant également plusieurs puissances étrangères.', NULL, 6),
('Accords de Bicesse', 'accords-bicesse-AO', '01991-05-31', '01991-05-31', 'Les accords de Bicesse prévoient un cessez-le-feu, la transformation des forces armées et l’organisation d’élections multipartites.', NULL, 14),
('Protocole de Lusaka et fin de la guerre civile', 'protocole-lusaka-fin-guerre-civile-AO', '02002-04-04', '02002-04-04', 'La mort de Jonas Savimbi et la signature du mémorandum de Luena mettent fin aux principales hostilités et ouvrent la voie à la paix en Angola.', NULL, 14);


-- BENIN --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Fondation du royaume du Dahomey', 'fondation-royaume-dahomey-BJ', '01620-01-01', '01620-12-31', 'Le royaume du Dahomey se forme sur le plateau d’Abomey et devient progressivement une puissance majeure de la région.', NULL, 16),
('Prise d’Allada par le Dahomey', 'prise-allada-dahomey-BJ', '01725-01-01', '01725-12-31', 'Le Dahomey conquiert Allada et renforce son contrôle sur les routes commerciales de la côte du golfe de Guinée.', NULL, 12),
('Développement du royaume du Dahomey', 'developpement-royaume-dahomey-BJ', '01700-01-01', '01800-12-31', 'Le royaume du Dahomey développe une administration centralisée, une armée puissante et un important réseau commercial.', NULL, 17),
('Développement du commerce à Ouidah', 'developpement-commerce-ouidah-BJ', '01700-01-01', '01800-12-31', 'Ouidah devient un important port commercial et l’un des principaux centres de la traite atlantique dans le golfe de Guinée.', NULL, 25),
('Traité franco-dahoméen de 1851', 'traite-franco-dahomeen-1851-BJ', '01851-11-01', '01851-11-01', 'La France et le royaume du Dahomey concluent un traité d’amitié et de commerce qui renforce les relations entre les deux parties.', NULL, 14),
('Premier protectorat français sur Porto-Novo', 'protectorat-francais-porto-novo-BJ', '01863-01-01', '01863-12-31', 'Le roi Toffa de Porto-Novo accepte un protectorat français dans un contexte de rivalités régionales.', NULL, 14),
('Installation française à Cotonou', 'installation-francaise-cotonou-BJ', '01863-01-01', '01863-12-31', 'Le roi Glèlè autorise les Français à établir une présence à Cotonou.', NULL, 17),
('Traité franco-dahoméen de 1878', 'traite-franco-dahomeen-1878-BJ', '01878-01-01', '01878-12-31', 'Un nouvel accord renforce les intérêts français sur la côte du Dahomey.', NULL, 14),
('Protectorat français sur Porto-Novo', 'protectorat-francais-porto-novo-1882-BJ', '01882-01-01', '01882-12-31', 'Le souverain de Porto-Novo signe un nouvel accord de protectorat avec la France.', NULL, 14),
('Première guerre franco-dahoméenne', 'premiere-guerre-franco-dahomeenne-BJ', '01890-02-01', '01890-10-04', 'Le royaume du Dahomey affronte les forces françaises dans le cadre du conflit pour le contrôle du littoral.', NULL, 6),
('Seconde guerre franco-dahoméenne', 'seconde-guerre-franco-dahomeenne-BJ', '01892-07-01', '01894-01-15', 'Les forces françaises affrontent le royaume du Dahomey et progressent jusqu’à Abomey.', NULL, 6),
('Chute du roi Béhanzin', 'chute-roi-behanzin-BJ', '01894-01-15', '01894-01-15', 'La prise d’Abomey entraîne la défaite du roi Béhanzin et la fin de l’indépendance du royaume du Dahomey.', NULL, 12),
('Création de la colonie du Dahomey et dépendances', 'creation-colonie-dahomey-BJ', '01894-06-22', '01894-06-22', 'La France crée officiellement la colonie du Dahomey et dépendances après la conquête du royaume.', NULL, 17),
('Rattachement au Soudan français puis à l’Afrique occidentale française', 'rattachement-afrique-occidentale-francaise-BJ', '01899-01-01', '01899-12-31', 'Le Dahomey est intégré à l’organisation administrative de l’Afrique occidentale française.', NULL, 12),
('Création du territoire du Dahomey', 'creation-territoire-dahomey-BJ', '01946-01-01', '01946-01-01', 'Le Dahomey devient un territoire d’outre-mer français après la réorganisation de l’empire colonial.', NULL, 17),
('Proclamation de la République du Dahomey', 'proclamation-republique-dahomey-BJ', '01958-12-04', '01958-12-04', 'Le Dahomey devient une république autonome au sein de la Communauté française.', NULL, 22),
('Indépendance du Dahomey', 'independance-dahomey-BJ', '01960-08-01', '01960-08-01', 'Le Dahomey accède à la souveraineté internationale et devient un État indépendant.', NULL, 11),
('Coup d’État de Christophe Soglo', 'coup-etat-christophe-soglo-BJ', '01963-10-28', '01963-10-28', 'Le colonel Christophe Soglo renverse le président Hubert Maga et met fin au premier gouvernement élu de l’indépendance.', NULL, 10),
('Coup d’État de Mathieu Kérékou', 'coup-etat-mathieu-kerekou-BJ', '01972-10-26', '01972-10-26', 'Mathieu Kérékou prend le pouvoir à la suite d’un coup d’État militaire et ouvre une nouvelle période politique.', NULL, 10),
('Création de la République populaire du Bénin', 'creation-republique-populaire-benin-BJ', '01975-11-30', '01975-11-30', 'Le Dahomey est rebaptisé République populaire du Bénin et adopte officiellement une orientation marxiste-léniniste.', NULL, 22);


-- BOTSWANA --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Développement des sociétés tswana', 'developpement-societes-tswana-BW', '01000-01-01', '01400-12-31', 'Les sociétés tswana développent progressivement des structures politiques organisées autour de chefferies et de communautés appelées merafe.', NULL, 17),
('Expansion de la culture du Grand Zimbabwe au Botswana', 'expansion-culture-grand-zimbabwe-BW', '01200-01-01', '01400-12-31', 'La culture du Grand Zimbabwe étend son influence commerciale et culturelle jusque dans l’est du territoire de l’actuel Botswana.', NULL, 17),
('Développement du royaume de Butua', 'developpement-royaume-butua-BW', '01450-01-01', '01650-12-31', 'Après le déclin du Grand Zimbabwe, le royaume de Butua devient une puissance régionale dans l’espace correspondant notamment à l’est du Botswana.', NULL, 16),
('Formation des chefferies tswana', 'formation-chefferies-tswana-BW', '01600-01-01', '01800-12-31', 'Plusieurs chefferies tswana importantes se consolident, notamment les Bakwena, Bangwaketse, Bakgatla et Bangwato.', NULL, 16),
('Expansion des Ngwato sous Khama', 'expansion-ngwato-khama-BW', '01840-01-01', '01870-12-31', 'Les Bangwato renforcent leur puissance politique dans le nord-est du territoire sous l’autorité de Khama III.', NULL, 5),
('Arrivée des missionnaires chrétiens', 'arrivee-missionnaires-chretiens-BW', '01841-01-01', '01841-12-31', 'Les missionnaires de la London Missionary Society commencent à établir une présence durable parmi les populations tswana.', NULL, 23),
('Protection britannique du Bechuanaland', 'protectorat-britannique-bechuanaland-BW', '01885-03-31', '01885-03-31', 'La Grande-Bretagne établit le protectorat du Bechuanaland à la demande de plusieurs dirigeants tswana qui cherchent une protection contre les menaces extérieures.', NULL, 13),
('Visite de Khama III, Sebele I et Bathoen I à Londres', 'visite-trois-dikgosi-londres-BW', '01895-01-01', '01895-12-31', 'Khama III, Sebele I et Bathoen I se rendent en Grande-Bretagne pour défendre l’autonomie de leurs territoires face aux projets d’annexion.', NULL, 22),
('Construction du chemin de fer du Bechuanaland', 'construction-chemin-fer-bechuanaland-BW', '01897-01-01', '01897-12-31', 'La construction de la ligne ferroviaire traversant le protectorat renforce les communications et les échanges commerciaux avec l’Afrique australe.', NULL, 17),
('Épidémie de peste bovine au Bechuanaland', 'epidemie-peste-bovine-bechuanaland-BW', '01896-01-01', '01897-12-31', 'Une importante épizootie de peste bovine provoque de lourdes pertes de bétail dans le protectorat.', NULL, 21),
('Transfert de la capitale des Bangwato à Serowe', 'transfert-capitale-bangwato-serowe-BW', '01902-01-01', '01902-12-31', 'Sous l’autorité de Khama III, la capitale des Bangwato est transférée de Phalatswe à Serowe, qui devient un important centre politique du Bechuanaland.', NULL, 22),
('Établissement de Serowe comme centre des Bangwato', 'etablissement-serowe-bangwato-BW', '01902-01-01', '01902-12-31', 'Serowe devient le principal centre des Bangwato et s’impose progressivement comme l’un des principaux pôles politiques du Bechuanaland.', NULL, 17),
('Création du Conseil consultatif africain', 'creation-conseil-consultatif-africain-BW', '01929-01-01', '01929-12-31', 'Une institution consultative est créée afin de permettre aux représentants africains du protectorat de participer davantage aux affaires administratives.', NULL, 17),
('Constitution du Bechuanaland de 1961', 'constitution-bechuanaland-1961-BW', '01961-03-01', '01961-03-01', 'Une nouvelle Constitution établit notamment la Chambre des chefs et réorganise les institutions politiques du protectorat.', NULL, 22),
('Création du Parti démocratique du Botswana', 'creation-parti-democratique-botswana-BW', '01962-01-01', '01962-01-01', 'Seretse Khama et ses alliés fondent le Botswana Democratic Party, qui participe à la transition politique vers l’autonomie.', NULL, 17),
('Autonomie interne du Bechuanaland', 'autonomie-interne-bechuanaland-BW', '01965-03-01', '01965-03-01', 'Le Bechuanaland devient autonome avec un gouvernement élu dirigé par Seretse Khama comme Premier ministre.', NULL, 22),
('Transfert de la capitale à Gaborone', 'transfert-capitale-gaborone-BW', '01965-01-01', '01965-01-01', 'Le siège du gouvernement est transféré de Mafikeng à Gaborone, nouvelle capitale située à l’intérieur du territoire du protectorat.', NULL, 22),
('Indépendance du Botswana', 'independance-botswana-BW', '01966-09-30', '01966-09-30', 'Le Bechuanaland devient la République indépendante du Botswana et Seretse Khama devient son premier président.', NULL, 11),
('Découverte des diamants d’Orapa', 'decouverte-diamants-orapa-BW', '01967-07-01', '01967-07-01', 'D’importants gisements de diamants sont découverts à Orapa, ouvrant une nouvelle période économique pour le Botswana.', NULL, 18),
('Adhésion du Botswana à l’Organisation des Nations unies', 'adhesion-botswana-onu-BW', '01966-10-17', '01966-10-17', 'Le Botswana devient membre de l’Organisation des Nations unies peu après son indépendance.', NULL, 15);

-- BURKINA FASO --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Fondation du royaume de Ouagadougou', 'fondation-royaume-ouagadougou-BF', '01100-01-01', '01100-12-31', 'Le royaume mossi de Ouagadougou se forme et devient progressivement l’un des principaux États de la région.', NULL, 16),
('Formation des royaumes mossi', 'formation-royaumes-mossi-BF', '01100-01-01', '01500-12-31', 'Plusieurs royaumes mossi se structurent dans l’espace correspondant à l’actuel Burkina Faso.', NULL, 16),
('Développement du royaume de Yatenga', 'developpement-royaume-yatenga-BF', '01400-01-01', '01600-12-31', 'Le royaume de Yatenga se consolide au nord et devient une importante puissance politique mossi.', NULL, 16),
('Arrivée des premiers missionnaires chrétiens', 'arrivee-missionnaires-chretiens-BF', '01900-01-01', '01900-12-31', 'Les premières missions chrétiennes s’implantent dans les territoires correspondant à l’actuel Burkina Faso.', NULL, 23),
('Conquête française des royaumes mossi', 'conquete-francaise-royaumes-mossi-BF', '01896-01-01', '01896-12-31', 'Les forces françaises soumettent progressivement les royaumes mossi et imposent leur domination coloniale.', NULL, 12),
('Création de la colonie de Haute-Volta', 'creation-colonie-haute-volta-BF', '01919-03-01', '01919-03-01', 'La France crée la colonie de Haute-Volta à partir de territoires auparavant administrés au sein de colonies voisines.', NULL, 17),
('Suppression de la colonie de Haute-Volta', 'suppression-colonie-haute-volta-BF', '01932-09-05', '01932-09-05', 'La colonie de Haute-Volta est supprimée et son territoire est réparti entre les colonies voisines.', NULL, 22),
('Rétablissement de la Haute-Volta', 'retablissement-haute-volta-BF', '01947-09-04', '01947-09-04', 'La colonie de Haute-Volta est rétablie dans ses frontières antérieures.', NULL, 22),
('Création de l’Union démocratique voltaïque', 'creation-union-democratique-voltaïque-BF', '01946-01-01', '01946-12-31', 'L’Union démocratique voltaïque devient un mouvement politique majeur de la Haute-Volta dans la période précédant l’indépendance.', NULL, 17),
('République autonome de Haute-Volta', 'republique-autonome-haute-volta-BF', '01958-12-11', '01958-12-11', 'La Haute-Volta devient une république autonome au sein de la Communauté française.', NULL, 22),
('Indépendance de la Haute-Volta', 'independance-haute-volta-BF', '01960-08-05', '01960-08-05', 'La Haute-Volta accède à l’indépendance et devient un État souverain.', NULL, 11),
('Adhésion de la Haute-Volta à l’ONU', 'adhesion-haute-volta-onu-BF', '01960-09-20', '01960-09-20', 'La Haute-Volta devient membre de l’Organisation des Nations unies peu après son indépendance.', NULL, 15),
('Coup d’État de Sangoulé Lamizana', 'coup-etat-sangoule-lamizana-BF', '01966-01-03', '01966-01-03', 'Le général Sangoulé Lamizana renverse le président Maurice Yaméogo à la suite d’une crise sociale et politique.', NULL, 10),
('Création de la République de Haute-Volta', 'creation-republique-haute-volta-BF', '01970-06-14', '01970-06-14', 'Une nouvelle Constitution instaure la Deuxième République de Haute-Volta.', NULL, 22),
('Coup d’État de Saye Zerbo', 'coup-etat-saye-zerbo-BF', '01980-11-25', '01980-11-25', 'Saye Zerbo renverse le président Sangoulé Lamizana lors d’un coup d’État militaire.', NULL, 10),
('Coup d’État de Thomas Sankara', 'coup-etat-thomas-sankara-BF', '01983-08-04', '01983-08-04', 'Thomas Sankara prend le pouvoir lors d’un coup d’État et lance un vaste programme de transformation politique et sociale.', NULL, 10),
('Changement de nom en Burkina Faso', 'changement-nom-burkina-faso-BF', '01984-08-04', '01984-08-04', 'Le pays abandonne le nom de Haute-Volta et adopte officiellement le nom de Burkina Faso.', NULL, 22),
('Assassinat de Thomas Sankara', 'assassinat-thomas-sankara-BF', '01987-10-15', '01987-10-15', 'Thomas Sankara est assassiné lors du coup d’État qui porte Blaise Compaoré au pouvoir.', NULL, 10),
('Insurrection burkinabè', 'insurrection-burkinabe-BF', '02014-10-28', '02014-10-31', 'Un vaste mouvement de protestation entraîne la chute du président Blaise Compaoré après 27 années au pouvoir.', NULL, 9),
('Coup d’État de 2022', 'coup-etat-burkina-faso-2022-BF', '02022-09-30', '02022-09-30', 'Le capitaine Ibrahim Traoré renverse le gouvernement de transition dirigé par Paul-Henri Sandaogo Damiba.', NULL, 10);


-- BURUNDI --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Formation du royaume du Burundi', 'formation-royaume-burundi-BI', '01500-01-01', '01500-12-31', 'Le royaume du Burundi se structure progressivement autour d’une monarchie dirigée par les mwami dans la région des Grands Lacs.', NULL, 16),
('Consolidation du royaume du Burundi', 'consolidation-royaume-burundi-BI', '01700-01-01', '01800-12-31', 'Le royaume du Burundi consolide son administration et étend son influence sur les territoires environnants.', NULL, 5),
('Arrivée des premiers missionnaires et explorateurs européens', 'arrivee-missionnaires-explorateurs-europeens-BI', '01856-01-01', '01856-12-31', 'Des explorateurs et missionnaires européens commencent à visiter la région du Burundi.', NULL, 18),
('Établissement de la domination allemande', 'domination-allemande-burundi-BI', '01899-01-01', '01899-12-31', 'Le Burundi passe sous administration allemande dans le cadre de l’Afrique orientale allemande.', NULL, 13),
('Traité de Kiganda', 'traite-kiganda-BI', '01903-06-06', '01903-06-06', 'Le mwami Mwezi Gisabo signe un traité de protection avec l’Allemagne, renforçant la présence allemande au Burundi.', NULL, 14),
('Occupation belge du Burundi', 'occupation-belge-burundi-BI', '01916-01-01', '01916-01-01', 'Les forces belges occupent le Burundi pendant la Première Guerre mondiale.', NULL, 13),
('Mandat belge sur le Ruanda-Urundi', 'mandat-belge-ruanda-urundi-BI', '01923-07-20', '01923-07-20', 'La Société des Nations confie à la Belgique le mandat sur le territoire du Ruanda-Urundi.', NULL, 22),
('Création du Conseil général du Ruanda-Urundi', 'creation-conseil-general-ruanda-urundi-BI', '01948-01-01', '01948-12-31', 'La Belgique introduit de nouvelles institutions consultatives dans le cadre de l’évolution politique du Ruanda-Urundi.', NULL, 17),
('Création de l’UPRONA', 'creation-uprona-BI', '01958-01-01', '01961-12-31', 'L’Union pour le progrès national, dirigée notamment par le prince Louis Rwagasore, devient le principal mouvement nationaliste burundais.', NULL, 17),
('Victoire de l’UPRONA aux élections législatives', 'victoire-uprona-elections-1961-BI', '01961-09-08', '01961-09-08', 'L’UPRONA remporte largement les premières élections législatives du Burundi et Louis Rwagasore devient Premier ministre.', NULL, 22),
('Assassinat de Louis Rwagasore', 'assassinat-louis-rwagasore-BI', '01961-10-13', '01961-10-13', 'Le prince Louis Rwagasore, figure majeure du mouvement indépendantiste, est assassiné à Bujumbura.', NULL, 2),
('Première Constitution du Royaume du Burundi', 'premiere-constitution-royaume-burundi-BI', '01961-11-23', '01961-11-23', 'La première Constitution du Royaume du Burundi est promulguée dans la période précédant l’indépendance.', NULL, 22),
('Indépendance du Burundi', 'independance-burundi-BI', '01962-07-01', '01962-07-01', 'Le Burundi accède à l’indépendance et devient une monarchie constitutionnelle dirigée par Mwambutsa IV.', NULL, 11),
('Adhésion du Burundi à l’ONU', 'adhesion-burundi-onu-BI', '01962-09-18', '01962-09-18', 'Le Burundi devient membre de l’Organisation des Nations unies quelques mois après son indépendance.', NULL, 22),
('Assassinat de Pierre Ngendandumwe', 'assassinat-pierre-ngendandumwe-BI', '01965-01-15', '01965-01-15', 'Le Premier ministre Pierre Ngendandumwe est assassiné dans un contexte de fortes tensions politiques.', NULL, 2),
('Coup d’État de 1966 et abolition de la monarchie', 'coup-etat-abolition-monarchie-burundi-BI', '01966-11-28', '01966-11-28', 'Michel Micombero renverse la monarchie et proclame la République du Burundi.', NULL, 10),
('Crise burundaise de 1972', 'crise-burundi-1972-BI', '01972-04-27', '01972-12-31', 'Une rébellion et les violences qui suivent provoquent une crise majeure au Burundi et d’importants déplacements de population.', NULL, 9),
('Coup d’État de Jean-Baptiste Bagaza', 'coup-etat-jean-baptiste-bagaza-BI', '01976-11-02', '01976-11-02', 'Jean-Baptiste Bagaza renverse Michel Micombero lors d’un coup d’État militaire.', NULL, 10),
('Coup d’État de Pierre Buyoya', 'coup-etat-pierre-buyoya-1987-BI', '01987-09-03', '01987-09-03', 'Pierre Buyoya renverse Jean-Baptiste Bagaza et prend la tête du pays.', NULL, 10),
('Assassinat de Melchior Ndadaye et début de la guerre civile', 'assassinat-melchior-ndadaye-guerre-civile-BI', '01993-10-21', '01993-10-21', 'L’assassinat du président Melchior Ndadaye déclenche une grave crise politique et le début de la guerre civile burundaise.', NULL, 6);


-- CAMEROUN --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Fondation du royaume de Bamoun', 'fondation-royaume-bamoun-CM', '01390-01-01', '01400-12-31', 'Le royaume de Bamoun se forme dans les hautes terres de l’ouest de l’actuel Cameroun et devient progressivement une puissance régionale.', NULL, 16),
('Expansion du royaume de Bamoun', 'expansion-royaume-bamoun-CM', '01600-01-01', '01800-12-31', 'Le royaume de Bamoun étend progressivement son influence et consolide son organisation politique autour de Foumban.', NULL, 5),
('Arrivée des missionnaires baptistes', 'arrivee-missionnaires-baptistes-CM', '01845-01-01', '01845-12-31', 'Les missionnaires baptistes commencent à établir des missions sur la côte camerounaise.', NULL, 23),
('Début de la présence allemande au Cameroun', 'debut-presence-allemande-cameroun-CM', '01884-07-12', '01884-07-12', 'L’Allemagne établit un protectorat sur une partie de la côte camerounaise, marquant le début de la colonisation allemande.', NULL, 13),
('Création du Kamerun allemand', 'creation-kamerun-allemand-CM', '01884-07-14', '01884-07-14', 'Les autorités allemandes consolident leur contrôle colonial sur le territoire du Cameroun.', NULL, 17),
('Révolte des Douala contre la domination allemande', 'revolte-douala-domination-allemande-CM', '01904-01-01', '01904-12-31', 'Les autorités allemandes font face à des résistances locales liées à leur politique coloniale et économique.', NULL, 9),
('Début de la Première Guerre mondiale au Cameroun', 'debut-guerre-mondiale-cameroun-CM', '01914-08-01', '01916-02-18', 'Les forces alliées affrontent les troupes allemandes au Cameroun pendant la Première Guerre mondiale.', NULL, 6),
('Partage du Cameroun entre la France et le Royaume-Uni', 'partage-cameroun-france-royaume-uni-CM', '01919-07-10', '01919-07-10', 'Après la défaite allemande, le Cameroun est partagé entre une zone française et une zone britannique sous mandat de la Société des Nations.', NULL, 22),
('Mandat français sur le Cameroun', 'mandat-francais-cameroun-CM', '01922-07-20', '01922-07-20', 'La Société des Nations confirme le mandat français sur la majeure partie du Cameroun.', NULL, 22),
('Création de l’Union des populations du Cameroun', 'creation-upc-cameroun-CM', '01948-04-10', '01948-04-10', 'L’Union des populations du Cameroun est fondée et devient un mouvement majeur du nationalisme camerounais.', NULL, 17),
('Début de l’insurrection de l’UPC', 'debut-insurrection-upc-CM', '01955-05-01', '01955-12-31', 'Les tensions entre l’UPC et les autorités coloniales dégénèrent en conflit et en répression.', NULL, 9),
('Proclamation de la République du Cameroun', 'proclamation-republique-cameroun-CM', '01958-01-01', '01958-01-01', 'Le Cameroun français obtient une large autonomie interne et évolue vers la souveraineté.', NULL, 22),
('Indépendance du Cameroun français', 'independance-cameroun-francais-CM', '01960-01-01', '01960-01-01', 'La République du Cameroun devient indépendante de la France avec Ahmadou Ahidjo comme premier président.', NULL, 11),
('Indépendance du Cameroun méridional britannique', 'independance-cameroun-meridional-britannique-CM', '01961-10-01', '01961-10-01', 'Le Cameroun méridional britannique rejoint la République du Cameroun, tandis que le Cameroun septentrional rejoint le Nigeria.', NULL, 11),
('Réunification du Cameroun', 'reunification-cameroun-CM', '01961-10-01', '01961-10-01', 'La République du Cameroun et le Cameroun méridional britannique forment la République fédérale du Cameroun.', NULL, 17),
('Création de la République unie du Cameroun', 'creation-republique-unie-cameroun-CM', '01972-05-20', '01972-05-20', 'Un référendum transforme la fédération en un État unitaire appelé République unie du Cameroun.', NULL, 22),
('Tentative de coup d’État contre Ahmadou Ahidjo', 'tentative-coup-etat-ahmadou-ahidjo-CM', '01984-04-06', '01984-04-06', 'Une tentative de coup d’État militaire échoue à Yaoundé contre le président Ahmadou Ahidjo.', NULL, 10),
('Démission d’Ahmadou Ahidjo et arrivée de Paul Biya', 'arrivee-paul-biya-pouvoir-CM', '01982-11-06', '01982-11-06', 'Ahmadou Ahidjo démissionne de la présidence et Paul Biya lui succède conformément aux dispositions constitutionnelles.', NULL, 22),
('Émeutes de 1990 et réformes multipartites', 'emeutes-reformes-multipartites-cameroun-CM', '01990-05-01', '01992-01-01', 'Des mouvements de contestation conduisent à la restauration du multipartisme et à l’organisation d’élections pluralistes.', NULL, 8),
('Adoption de la Constitution de 1996', 'constitution-cameroun-1996-CM', '01996-01-18', '01996-01-18', 'Une nouvelle Constitution réorganise les institutions camerounaises et prévoit notamment la décentralisation.', NULL, 22);


-- CAP-VERT --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Découverte des îles du Cap-Vert par les Portugais', 'decouverte-cap-vert-portugais-CV', '01460-01-01', '01460-12-31', 'Les navigateurs portugais découvrent l’archipel du Cap-Vert au cours des expéditions portugaises sur la côte ouest-africaine.', NULL, 18),
('Début du peuplement de Santiago', 'peuplement-santiago-cap-vert-CV', '01462-01-01', '01462-12-31', 'Le peuplement de l’île de Santiago commence et marque le début de l’occupation permanente de l’archipel.', NULL, 16),
('Création de Ribeira Grande', 'creation-ribeira-grande-cap-vert-CV', '01462-01-01', '01462-12-31', 'Ribeira Grande, sur l’île de Santiago, devient le premier grand centre administratif et commercial de l’archipel.', NULL, 16),
('Développement de la traite atlantique au Cap-Vert', 'developpement-traite-atlantique-cap-vert-CV', '01500-01-01', '01700-12-31', 'Le Cap-Vert devient un important entrepôt commercial sur les routes atlantiques et participe au développement de la traite des esclaves.', NULL, 25),
('Attaque de Francis Drake contre Santiago', 'attaque-francis-drake-santiago-CV', '01580-11-15', '01580-11-15', 'Le corsaire anglais Francis Drake attaque Santiago et pille Ribeira Grande.', NULL, 13),
('Déclin de Ribeira Grande', 'declin-ribeira-grande-CV', '01600-01-01', '01700-12-31', 'Les attaques maritimes, la concurrence commerciale et les transformations des routes atlantiques entraînent le déclin progressif de Ribeira Grande.', NULL, 25),
('Établissement de Praia comme centre administratif', 'etablissement-praia-centre-administratif-CV', '01770-01-01', '01770-12-31', 'Praia s’impose progressivement comme le principal centre administratif de l’archipel au détriment de Ribeira Grande.', NULL, 22),
('Transfert de la capitale à Praia', 'transfert-capitale-praia-CV', '01776-01-01', '01776-12-31', 'Praia devient officiellement le principal siège administratif du Cap-Vert.', NULL, 22),
('Création du port de Mindelo', 'creation-port-mindelo-CV', '01830-01-01', '01830-12-31', 'Le port de Mindelo, sur l’île de São Vicente, se développe comme station de ravitaillement pour les navires de l’Atlantique.', NULL, 17),
('Ouverture du câble sous-marin à Mindelo', 'cable-sous-marin-mindelo-CV', '01872-01-01', '01872-12-31', 'Mindelo devient un point important du réseau télégraphique sous-marin reliant l’Europe, l’Afrique et l’Amérique du Sud.', NULL, 19),
('Construction du chemin de fer de Praia', 'chemin-fer-praia-cap-vert-CV', '01885-01-01', '01885-12-31', 'Des infrastructures ferroviaires sont développées autour de Praia afin de faciliter le transport des marchandises.', NULL, 19),
('Installation de la station de télégraphie de São Vicente', 'station-telegraphie-sao-vicente-CV', '01890-01-01', '01890-12-31', 'São Vicente renforce son rôle stratégique grâce au développement des communications télégraphiques internationales.', NULL, 19),
('Ouverture du camp de Tarrafal', 'ouverture-camp-tarrafal-CV', '01936-10-29', '01936-10-29', 'Le Portugal ouvre le camp de concentration du Tarrafal sur l’île de Santiago pour y emprisonner notamment des opposants politiques.', NULL, 22),
('Transformation du Cap-Vert en province ultramarine portugaise', 'province-ultramarine-cap-vert-CV', '01951-06-11', '01951-06-11', 'Le statut administratif du Cap-Vert est modifié et l’archipel devient une province ultramarine du Portugal.', NULL, 22),
('Création du PAIGC', 'creation-paigc-CV', '01956-09-19', '01956-09-19', 'Amílcar Cabral et ses compagnons fondent le Parti africain pour l’indépendance de la Guinée et du Cap-Vert.', NULL, 17),
('Réouverture du camp de Tarrafal', 'reouverture-camp-tarrafal-CV', '01962-01-01', '01962-12-31', 'Le camp de Tarrafal est rouvert et sert notamment à emprisonner des militants anticoloniaux originaires des colonies portugaises.', NULL, 22),
('Accord Portugal-PAIGC sur l’indépendance du Cap-Vert', 'accord-portugal-paigc-cap-vert-CV', '01974-12-19', '01974-12-19', 'Le Portugal et le PAIGC concluent un accord reconnaissant le droit du peuple cap-verdien à l’autodétermination et prévoyant un gouvernement de transition.', NULL, 14),
('Indépendance du Cap-Vert', 'independance-cap-vert-CV', '01975-07-05', '01975-07-05', 'Le Cap-Vert proclame son indépendance du Portugal à Praia après plus de cinq siècles de présence portugaise.', NULL, 11),
('Premières élections multipartites', 'premieres-elections-multipartites-cap-vert-CV', '01991-01-13', '01991-01-13', 'Les premières élections multipartites de l’histoire du Cap-Vert mettent fin au système politique à parti unique.', NULL, 22),
('Adoption de la Constitution de 1992', 'constitution-cap-vert-1992-CV', '01992-09-25', '01992-09-25', 'Une nouvelle Constitution établit le cadre institutionnel de la République démocratique du Cap-Vert.', NULL, 22);


-- COMORES --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Développement des cités swahilies des Comores', 'developpement-cites-swahilies-comores-KM', '01100-01-01', '01400-12-31', 'Les îles des Comores s’intègrent aux réseaux commerciaux swahilis reliant l’Afrique orientale, l’Arabie et Madagascar.', NULL, 25),
('Islamisation progressive de l’archipel', 'islamisation-comores-KM', '01100-01-01', '01500-12-31', 'L’islam se diffuse progressivement dans les îles des Comores grâce aux marchands et aux réseaux religieux de l’océan Indien.', NULL, 23),
('Établissement du sultanat de Ndzuwani', 'etablissement-sultanat-ndzuwani-KM', '01500-01-01', '01500-12-31', 'Le sultanat d’Anjouan se consolide et devient l’un des principaux pouvoirs politiques de l’archipel.', NULL, 16),
('Développement du sultanat de Ngazidja', 'developpement-sultanat-ngazidja-KM', '01500-01-01', '01700-12-31', 'Les différents sultanats de Grande Comore se développent et structurent durablement la vie politique de l’île.', NULL, 16),
('Développement du commerce maritime comorien', 'developpement-commerce-maritime-comorien-KM', '01500-01-01', '01800-12-31', 'Les ports comoriens participent activement aux échanges de marchandises et de personnes dans l’océan Indien occidental.', NULL, 25),
('Arrivée de navigateurs européens aux Comores', 'arrivee-navigateurs-europeens-comores-KM', '01500-01-01', '01600-12-31', 'Les navigateurs portugais et d’autres Européens commencent à fréquenter les routes maritimes proches de l’archipel.', NULL, 18),
('Rivalités entre sultanats comoriens', 'rivalites-sultanats-comoriens-KM', '01700-01-01', '01800-12-31', 'Les rivalités entre les différents sultanats des îles entraînent plusieurs conflits et changements d’influence politique.', NULL, 9),
('Installation de colons européens à Mayotte', 'installation-europeens-mayotte-KM', '01840-01-01', '01840-12-31', 'La France établit progressivement son influence à Mayotte dans le contexte de l’expansion coloniale dans l’océan Indien.', NULL, 13),
('Cession de Mayotte à la France', 'cession-mayotte-france-KM', '01841-04-25', '01841-04-25', 'Le sultan Andriantsoly cède Mayotte à la France, qui établit une présence coloniale durable dans l’archipel.', NULL, 14),
('Protectorat français sur Anjouan', 'protectorat-francais-anjouan-KM', '01886-01-01', '01886-12-31', 'La France impose progressivement son protectorat sur le sultanat d’Anjouan.', NULL, 14),
('Protectorat français sur Grande Comore', 'protectorat-francais-grande-comore-KM', '01886-01-01', '01886-12-31', 'La France étend son influence à Grande Comore et place les pouvoirs locaux sous protection française.', NULL, 14),
('Création du protectorat français des Comores', 'creation-protectorat-francais-comores-KM', '01896-01-01', '01896-12-31', 'Les différentes îles de l’archipel passent progressivement sous administration et protection françaises.', NULL, 17),
('Éruption du volcan Karthala', 'eruption-volcan-karthala-comores-KM', '01906-01-01', '01906-12-31', 'Une importante éruption du volcan Karthala affecte Grande Comore et illustre l’activité volcanique majeure de l’archipel.', NULL, 20),
('Création de la colonie de Madagascar et dépendances', 'creation-colonie-madagascar-dependances-comores-KM', '01912-01-01', '01912-12-31', 'Les Comores sont intégrées administrativement à la colonie française de Madagascar et dépendances.', NULL, 17),
('Transfert administratif des Comores vers Madagascar', 'transfert-administration-comores-madagascar-KM', '01912-01-01', '01912-12-31', 'L’administration coloniale française rattache officiellement les Comores à Madagascar.', NULL, 22),
('Soulèvement d’Anjouan contre la présence française', 'soulevement-anjouan-presence-francaise-KM', '01915-01-01', '01915-12-31', 'Une importante révolte éclate à Anjouan contre l’administration coloniale française et les conditions imposées à la population locale.', NULL, 9),
('Séparation administrative des Comores et de Madagascar', 'separation-administrative-comores-madagascar-KM', '01946-01-01', '01946-12-31', 'Les Comores obtiennent un statut administratif distinct au sein de l’empire colonial français.', NULL, 22),
('Autonomie interne des Comores', 'autonomie-interne-comores-KM', '01961-01-01', '01961-12-31', 'Les Comores obtiennent une autonomie interne accrue dans le cadre de leur évolution vers l’indépendance.', NULL, 22),
('Indépendance des Comores', 'independance-comores-KM', '01975-07-06', '01975-07-06', 'Les Comores proclament leur indépendance de la France, tandis que Mayotte reste sous administration française.', NULL, 11),
('Coup d’État et prise de pouvoir d’Ali Soilih', 'coup-etat-ali-soilih-KM', '01975-08-03', '01975-08-03', 'Un coup d’État renverse le président Ahmed Abdallah et porte Ali Soilih au pouvoir.', NULL, 10);


-- CONGO --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Expansion des peuples bantous dans le bassin du Congo', 'expansion-peuples-bantous-bassin-congo-CG', '01000-01-01', '01500-12-31', 'Les migrations et l’expansion de populations bantouphones contribuent à la formation de nombreuses communautés dans le territoire de l’actuel Congo.', NULL, 17),
('Développement des royaumes du bassin du Congo', 'developpement-royaumes-bassin-congo-CG', '01200-01-01', '01500-12-31', 'Des formations politiques organisées se développent dans le bassin du Congo et structurent progressivement les échanges régionaux.', NULL, 16),
('Formation du royaume de Loango', 'formation-royaume-loango-CG', '01400-01-01', '01500-12-31', 'Le royaume de Loango se forme sur la côte atlantique et devient une puissance politique et commerciale importante de la région.', NULL, 16),
('Développement du royaume de Kongo', 'developpement-royaume-kongo-congo-CG', '01400-01-01', '01600-12-31', 'Le royaume de Kongo étend son influence dans le bassin inférieur du Congo et sur des territoires correspondant notamment à l’actuel Congo.', NULL, 16),
('Premiers contacts portugais avec le royaume de Kongo', 'premiers-contacts-portugais-kongo-CG', '01483-01-01', '01483-12-31', 'Les expéditions portugaises de Diogo Cão établissent des contacts avec les populations et pouvoirs du bassin du Congo.', NULL, 18),
('Christianisation du royaume de Kongo', 'christianisation-royaume-kongo-CG', '01491-01-01', '01491-12-31', 'Le christianisme se diffuse à la cour du royaume de Kongo à la suite des contacts avec les Portugais.', NULL, 23),
('Développement du commerce côtier de Loango', 'developpement-commerce-loango-CG', '01500-01-01', '01800-12-31', 'Les ports du royaume de Loango participent aux réseaux commerciaux reliant l’intérieur de l’Afrique à l’Atlantique.', NULL, 25),
('Développement de la traite atlantique sur la côte de Loango', 'developpement-traite-atlantique-loango-CG', '01600-01-01', '01800-12-31', 'Les ports de la côte de Loango sont intégrés aux réseaux de la traite atlantique des esclaves.', NULL, 25),
('Consolidation du royaume de Loango', 'consolidation-royaume-loango-CG', '01600-01-01', '01800-12-31', 'Le royaume de Loango consolide son organisation politique et son rôle dans le commerce régional et atlantique.', NULL, 5),
('Arrivée de missionnaires européens dans le bassin du Congo', 'arrivee-missionnaires-europeens-congo-CG', '01800-01-01', '01800-12-31', 'Les missions chrétiennes européennes commencent à s’implanter durablement dans les régions côtières et fluviales.', NULL, 23),
('Expéditions de Pierre Savorgnan de Brazza', 'expeditions-pierre-savorgnan-de-brazza-CG', '01880-01-01', '01885-12-31', 'Pierre Savorgnan de Brazza explore le bassin du Congo et établit des relations avec plusieurs dirigeants locaux.', NULL, 18),
('Traité de Makoko', 'traite-makoko-CG', '01880-09-10', '01880-09-10', 'Le traité conclu avec le roi Makoko permet à la France d’établir une influence politique sur la rive droite du Congo.', NULL, 14),
('Fondation de Brazzaville', 'fondation-brazzaville-CG', '01880-10-03', '01880-10-03', 'Pierre Savorgnan de Brazza fonde un poste français sur la rive droite du fleuve Congo, à l’origine de Brazzaville.', NULL, 16),
('Création du Congo français', 'creation-congo-francais-CG', '01890-01-01', '01890-12-31', 'La France organise progressivement ses possessions du bassin du Congo en une entité coloniale appelée Congo français.', NULL, 17),
('Création de l’Afrique-Équatoriale française', 'creation-afrique-equatoriale-francaise-CG', '01910-01-01', '01910-12-31', 'Le Congo français est intégré à la fédération de l’Afrique-Équatoriale française avec le Gabon, l’Oubangui-Chari et le Tchad.', NULL, 17),
('Première Guerre mondiale et révoltes au Moyen-Congo', 'premiere-guerre-mondiale-revoltes-moyen-congo-CG', '01914-01-01', '01918-12-31', 'La Première Guerre mondiale entraîne des réquisitions et des résistances dans les territoires du Moyen-Congo.', NULL, 9),
('Construction du chemin de fer Congo-Océan', 'construction-chemin-fer-congo-ocean-CG', '01921-01-01', '01934-07-01', 'La construction du chemin de fer Congo-Océan relie Brazzaville à la côte et mobilise une main-d’œuvre considérable.', NULL, 19),
('Achèvement du chemin de fer Congo-Océan', 'achevement-chemin-fer-congo-ocean-CG', '01934-07-01', '01934-07-01', 'La ligne du chemin de fer Congo-Océan est achevée et renforce les échanges entre Brazzaville et le port de Pointe-Noire.', NULL, 17),
('Fondation de Pointe-Noire', 'fondation-pointe-noire-CG', '01922-01-01', '01922-12-31', 'Pointe-Noire se développe comme port maritime majeur du Moyen-Congo et devient un centre économique important.', NULL, 16),
('Appel du général de Gaulle à Brazzaville', 'appel-general-de-gaulle-brazzaville-CG', '01940-10-27', '01940-10-27', 'Brazzaville devient un centre politique majeur de la France libre en Afrique pendant la Seconde Guerre mondiale.', NULL, 22),
('Conférence de Brazzaville', 'conference-brazzaville-CG', '01944-01-30', '01944-02-08', 'La conférence de Brazzaville réunit des représentants de la France libre et de l’empire colonial pour discuter de l’évolution politique des colonies françaises.', NULL, 22),
('Création de l’Union de la jeunesse congolaise', 'creation-union-jeunesse-congolaise-CG', '01947-01-01', '01947-12-31', 'Des organisations politiques et sociales nouvelles se développent au Moyen-Congo dans le contexte de l’après-guerre.', NULL, 17),
('Création du Parti progressiste congolais', 'creation-parti-progressiste-congolais-CG', '01956-01-01', '01956-12-31', 'Le Parti progressiste congolais de Jean-Félix Tchicaya devient l’un des principaux mouvements politiques du Moyen-Congo.', NULL, 17),
('Autonomie interne de la République du Congo', 'autonomie-interne-republique-congo-CG', '01958-11-28', '01958-11-28', 'Le Moyen-Congo devient une république autonome au sein de la Communauté française.', NULL, 22),
('Proclamation de la République du Congo', 'proclamation-republique-congo-CG', '01958-11-28', '01958-11-28', 'La République du Congo est proclamée dans le cadre de l’évolution politique menant à l’indépendance.', NULL, 22),
('Indépendance de la République du Congo', 'independance-republique-congo-CG', '01960-08-15', '01960-08-15', 'La République du Congo devient indépendante de la France et Fulbert Youlou devient son premier président.', NULL, 11),
('Adhésion du Congo à l’ONU', 'adhesion-congo-onu-CG', '01960-09-20', '01960-09-20', 'La République du Congo devient membre de l’Organisation des Nations unies.', NULL, 15),
('Création de l’Union de la jeunesse congolaise', 'creation-union-jeunesse-congolaise-1960-CG', '01960-01-01', '01960-12-31', 'Les organisations de jeunesse participent à la structuration de la vie politique du Congo indépendant.', NULL, 17),
('Révolution des Trois Glorieuses', 'revolution-trois-glorieuses-CG', '01963-08-13', '01963-08-15', 'Des manifestations et une mobilisation syndicale entraînent la démission du président Fulbert Youlou.', NULL, 8),
('Création de la République populaire du Congo', 'creation-republique-populaire-congo-CG', '01969-12-31', '01969-12-31', 'Le Congo adopte officiellement le régime de République populaire du Congo sous la direction de Marien Ngouabi.', NULL, 22),
('Fondation du Parti congolais du travail', 'fondation-parti-congolais-travail-CG', '01969-12-29', '01969-12-29', 'Le Parti congolais du travail est créé et devient le parti dirigeant de la République populaire du Congo.', NULL, 17),
('Assassinat de Marien Ngouabi', 'assassinat-marien-ngouabi-CG', '01977-03-18', '01977-03-18', 'Le président Marien Ngouabi est assassiné à Brazzaville dans un contexte de crise politique.', NULL, 2),
('Création du Comité militaire du parti', 'creation-comite-militaire-parti-CG', '01977-03-18', '01977-03-18', 'Un Comité militaire du parti prend le contrôle du pouvoir après l’assassinat de Marien Ngouabi.', NULL, 22),
('Arrivée au pouvoir de Denis Sassou-Nguesso', 'arrivee-pouvoir-denis-sassou-nguesso-CG', '01979-02-05', '01979-02-05', 'Denis Sassou-Nguesso devient président de la République populaire du Congo.', NULL, 22),
('Adoption d’une nouvelle Constitution en 1992', 'constitution-congo-1992-CG', '01992-06-15', '01992-06-15', 'Une nouvelle Constitution accompagne la transition du Congo vers le multipartisme et un système politique pluraliste.', NULL, 22),
('Premières élections présidentielles multipartites', 'premieres-elections-presidentielles-multipartites-congo-CG', '01992-08-09', '01992-08-16', 'Le Congo organise ses premières élections présidentielles pluralistes depuis l’instauration du régime à parti unique.', NULL, 22),
('Élection de Pascal Lissouba', 'election-pascal-lissouba-CG', '01992-08-16', '01992-08-16', 'Pascal Lissouba remporte le second tour de l’élection présidentielle et devient président de la République du Congo.', NULL, 22),
('Guerre civile de 1993', 'guerre-civile-congo-1993-CG', '01993-11-01', '01994-01-01', 'Des affrontements politiques armés opposent plusieurs forces organisées autour des principaux partis politiques congolais.', NULL, 6),
('Guerre civile du Congo de 1997', 'guerre-civile-congo-1997-CG', '01997-06-05', '01997-10-15', 'Un conflit armé oppose les forces fidèles à Pascal Lissouba à celles de Denis Sassou-Nguesso et provoque une grave crise nationale.', NULL, 6),
('Retour de Denis Sassou-Nguesso au pouvoir', 'retour-denis-sassou-nguesso-pouvoir-CG', '01997-10-15', '01997-10-15', 'Denis Sassou-Nguesso reprend le pouvoir à Brazzaville à l’issue de la guerre civile de 1997.', NULL, 22),
('Accord de cessez-le-feu de 1999', 'accord-cessez-feu-congo-1999-CG', '01999-12-29', '01999-12-29', 'Un accord contribue à mettre fin aux principales hostilités de la guerre civile congolaise.', NULL, 14),
('Adoption de la Constitution de 2002', 'constitution-congo-2002-CG', '02002-01-20', '02002-01-20', 'Une nouvelle Constitution établit les institutions de la République du Congo après la période de guerres civiles.', NULL, 22),
('Élection présidentielle de 2002', 'election-presidentielle-congo-2002-CG', '02002-03-10', '02002-03-10', 'Denis Sassou-Nguesso est élu président lors de l’élection présidentielle organisée après la guerre civile.', NULL, 22),
('Fin du conflit dans le Pool', 'fin-conflit-pool-congo-CG', '02003-03-17', '02003-03-17', 'Un accord de cessez-le-feu met fin aux principales opérations armées dans la région du Pool.', NULL, 14),
('Élection présidentielle de 2009', 'election-presidentielle-congo-2009-CG', '02009-07-12', '02009-07-12', 'Une élection présidentielle est organisée au Congo dans le cadre du système politique établi par la Constitution de 2002.', NULL, 22),
('Adoption de la Constitution de 2015', 'constitution-congo-2015-CG', '02015-10-25', '02015-10-25', 'Un référendum constitutionnel approuve une nouvelle Constitution de la République du Congo.', NULL, 22),
('Élection présidentielle de 2016', 'election-presidentielle-congo-2016-CG', '02016-03-20', '02016-03-20', 'Une élection présidentielle est organisée après l’adoption de la nouvelle Constitution.', NULL, 22),
('Réélection présidentielle de 2021', 'reelection-presidentielle-congo-2021-CG', '02021-03-21', '02021-03-21', 'Une nouvelle élection présidentielle est organisée en République du Congo.', NULL, 22),
('Adoption d’une nouvelle loi électorale', 'adoption-loi-electorale-congo-CG', '02022-01-01', '02022-12-31', 'Les institutions congolaises poursuivent la modernisation du cadre juridique régissant les élections nationales.', NULL, 22),
('Développement de l’industrie pétrolière congolaise', 'developpement-industrie-petroliere-congo-CG', '01970-01-01', '02000-12-31', 'L’exploitation pétrolière devient progressivement un secteur central de l’économie de la République du Congo.', NULL, 25);


-- COTE D'IVOIRE --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Développement des sociétés de l’âge du fer en Côte d’Ivoire', 'developpement-societes-age-fer-cote-ivoire-CI', '01000-01-01', '01500-12-31', 'Les populations établies sur le territoire de l’actuelle Côte d’Ivoire développent progressivement la métallurgie du fer, l’agriculture et des réseaux d’échanges régionaux.', NULL, 17),
('Expansion des peuples akan', 'expansion-peuples-akan-CI', '01200-01-01', '01600-12-31', 'Des populations akan s’étendent progressivement dans le sud et le centre du territoire correspondant à l’actuelle Côte d’Ivoire.', NULL, 16),
('Développement des réseaux commerciaux transsahariens', 'developpement-commerce-transsaharien-CI', '01200-01-01', '01800-12-31', 'Les régions septentrionales de l’actuelle Côte d’Ivoire participent aux réseaux commerciaux reliant le Sahel aux régions forestières du sud.', NULL, 25),
('Formation du royaume de Kong', 'formation-royaume-kong-CI', '01700-01-01', '01800-12-31', 'Le royaume de Kong se développe dans le nord-est de l’actuelle Côte d’Ivoire et devient un important centre politique et commercial.', NULL, 16),
('Développement du royaume de Sanwi', 'developpement-royaume-sanwi-CI', '01700-01-01', '01800-12-31', 'Le royaume de Sanwi se consolide dans le sud-est de l’actuelle Côte d’Ivoire et participe activement aux échanges côtiers.', NULL, 16),
('Arrivée des premiers missionnaires européens', 'arrivee-missionnaires-europeens-cote-ivoire-CI', '01840-01-01', '01840-12-31', 'Les premiers missionnaires chrétiens européens établissent des contacts avec les populations de la côte ivoirienne.', NULL, 23),
('Traités entre la France et les royaumes côtiers', 'traites-france-royaumes-cotiers-cote-ivoire-CI', '01840-01-01', '01895-12-31', 'La France conclut progressivement des traités avec plusieurs autorités locales afin d’étendre son influence sur la côte ivoirienne.', NULL, 14),
('Création du comptoir de Grand-Bassam', 'creation-comptoir-grand-bassam-CI', '01840-01-01', '01840-12-31', 'Grand-Bassam devient un important comptoir commercial français sur la côte du golfe de Guinée.', NULL, 17),
('Création de la colonie de Côte d’Ivoire', 'creation-colonie-cote-ivoire-CI', '01893-03-10', '01893-03-10', 'La France crée officiellement la colonie de Côte d’Ivoire et organise son administration coloniale.', NULL, 17),
('Conquête française de la Côte d’Ivoire', 'conquete-francaise-cote-ivoire-CI', '01893-01-01', '01902-12-31', 'Les forces françaises étendent leur contrôle sur l’intérieur du territoire et affrontent plusieurs résistances locales.', NULL, 12),
('Résistance de Samory Touré en Côte d’Ivoire', 'resistance-samory-toure-cote-ivoire-CI', '01898-01-01', '01898-09-29', 'Les forces de Samory Touré résistent à l’expansion française avant la capture du chef de guerre en 1898.', NULL, 9),
('Fondation de Bingerville', 'fondation-bingerville-CI', '01903-01-01', '01903-12-31', 'Bingerville devient le principal centre administratif de la colonie de Côte d’Ivoire après le déclin de Grand-Bassam.', NULL, 16),
('Création du chemin de fer Abidjan-Niger', 'creation-chemin-fer-abidjan-niger-CI', '01907-01-01', '01907-12-31', 'La construction du chemin de fer reliant Abidjan à l’intérieur de l’Afrique occidentale française commence et transforme les échanges régionaux.', NULL, 19),
('Fondation d’Abidjan', 'fondation-abidjan-CI', '01910-01-01', '01910-12-31', 'Abidjan se développe rapidement autour de son port et des infrastructures ferroviaires de la colonie.', NULL, 16),
('Création de l’AOF', 'creation-afrique-occidentale-francaise-CI', '01904-01-01', '01904-01-01', 'La Côte d’Ivoire est intégrée à l’organisation fédérale de l’Afrique occidentale française.', NULL, 17),
('Création du Parti démocratique de Côte d’Ivoire', 'creation-pdci-CI', '01946-10-09', '01946-10-09', 'Félix Houphouët-Boigny participe à la fondation du Parti démocratique de Côte d’Ivoire, mouvement majeur de la vie politique ivoirienne.', NULL, 17),
('Autonomie interne de la Côte d’Ivoire', 'autonomie-interne-cote-ivoire-CI', '01958-12-04', '01958-12-04', 'La Côte d’Ivoire devient une république autonome au sein de la Communauté française.', NULL, 22),
('Indépendance de la Côte d’Ivoire', 'independance-cote-ivoire-CI', '01960-08-07', '01960-08-07', 'La Côte d’Ivoire accède à l’indépendance et Félix Houphouët-Boigny devient son premier président.', NULL, 11),
('Crise politique de 1990 et retour au multipartisme', 'crise-politique-multipartisme-cote-ivoire-CI', '01990-01-01', '01990-12-31', 'Sous la pression de mouvements sociaux et politiques, le système politique ivoirien évolue vers le multipartisme.', NULL, 22),
('Coup d’État de 1999', 'coup-etat-cote-ivoire-1999-CI', '01999-12-24', '01999-12-24', 'Un coup d’État militaire renverse le président Henri Konan Bédié et installe un régime de transition dirigé par Robert Guéï.', NULL, 10);


-- DJIBOUTI --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Développement des royaumes et cités de la région d’Afar', 'developpement-royaumes-cites-afar-DJ', '01000-01-01', '01500-12-31', 'Les populations de la région correspondant à l’actuel Djibouti développent des chefferies et des réseaux commerciaux liés aux routes de la mer Rouge.', NULL, 16),
('Développement des routes commerciales de la mer Rouge', 'developpement-routes-commerciales-mer-rouge-DJ', '01200-01-01', '01700-12-31', 'La région de Djibouti devient un espace de passage important entre la mer Rouge, l’Éthiopie et la péninsule Arabique.', NULL, 25),
('Diffusion de l’islam dans la région de Djibouti', 'diffusion-islam-region-djibouti-DJ', '01200-01-01', '01500-12-31', 'L’islam se diffuse progressivement dans la région grâce aux marchands et aux réseaux religieux de la mer Rouge et de l’océan Indien.', NULL, 23),
('Développement du sultanat d’Adal', 'developpement-sultanat-adal-DJ', '01400-01-01', '01600-12-31', 'Le sultanat d’Adal étend son influence sur la région de la Corne de l’Afrique et contrôle une partie des routes commerciales proches du golfe d’Aden.', NULL, 16),
('Développement du commerce de Zeila', 'developpement-commerce-zeila-DJ', '01400-01-01', '01800-12-31', 'Zeila devient un important port commercial de la région, reliant les marchés de la Corne de l’Afrique à ceux de la péninsule Arabique.', NULL, 25),
('Arrivée des navigateurs européens dans le golfe d’Aden', 'arrivee-navigateurs-europeens-golfe-aden-DJ', '01500-01-01', '01600-12-31', 'Les navigateurs portugais et d’autres Européens fréquentent progressivement les routes maritimes du golfe d’Aden.', NULL, 18),
('Rivalités entre puissances locales dans la région afar', 'rivalites-puissances-locales-region-afar-DJ', '01700-01-01', '01800-12-31', 'Les rivalités entre sultanats et chefferies de la région influencent le contrôle des routes commerciales et des points d’eau.', NULL, 9),
('Début de l’influence française dans le golfe d’Aden', 'debut-influence-francaise-golfe-aden-DJ', '01863-01-01', '01863-12-31', 'La France commence à établir des relations commerciales et diplomatiques avec les autorités locales de la région du golfe d’Aden.', NULL, 13),
('Achat d’Obock par la France', 'achat-obock-france-DJ', '01862-03-11', '01862-03-11', 'La France obtient le territoire d’Obock par un accord conclu avec le sultan de Tadjourah, marquant le début de sa présence territoriale durable.', NULL, 14),
('Création du territoire d’Obock', 'creation-territoire-obock-DJ', '01864-01-01', '01864-12-31', 'La France organise son implantation autour d’Obock et établit progressivement une administration coloniale dans la région.', NULL, 17),
('Traité franco-britannique sur le golfe de Tadjourah', 'traite-franco-britannique-golfe-tadjourah-DJ', '01887-01-01', '01887-01-01', 'Un accord entre la France et le Royaume-Uni contribue à préciser leurs zones d’influence dans la région du golfe d’Aden.', NULL, 14),
('Création de la Côte française des Somalis', 'creation-cote-francaise-somalis-DJ', '01894-01-01', '01894-12-31', 'La France organise officiellement sa colonie autour de Djibouti et de la Côte française des Somalis.', NULL, 17),
('Fondation de Djibouti', 'fondation-djibouti-DJ', '01886-01-01', '01886-12-31', 'La ville de Djibouti se développe comme nouveau centre portuaire et administratif de la présence française dans la région.', NULL, 16),
('Construction du chemin de fer Djibouti-Addis-Abeba', 'construction-chemin-fer-djibouti-addis-abeba-DJ', '01897-01-01', '01917-01-01', 'La construction du chemin de fer reliant Djibouti à Addis-Abeba renforce considérablement le rôle commercial du port de Djibouti.', NULL, 19),
('Création du port moderne de Djibouti', 'creation-port-moderne-djibouti-DJ', '01910-01-01', '01910-12-31', 'Les infrastructures portuaires de Djibouti sont développées afin de soutenir le commerce avec l’Éthiopie et les routes maritimes internationales.', NULL, 17),
('Ralliement de Djibouti à la France libre', 'ralliement-djibouti-france-libre-DJ', '01942-12-26', '01942-12-26', 'Après une période de blocus et de tensions pendant la Seconde Guerre mondiale, la Côte française des Somalis se rallie à la France libre.', NULL, 22),
('Référendum sur l’autonomie de 1958', 'referendum-autonomie-djibouti-1958-DJ', '01958-09-28', '01958-09-28', 'La population de la Côte française des Somalis participe au référendum organisé dans le cadre de la Communauté française.', NULL, 22),
('Création du Territoire français des Afars et des Issas', 'creation-territoire-francais-afars-issas-DJ', '01967-07-05', '01967-07-05', 'La Côte française des Somalis est renommée Territoire français des Afars et des Issas.', NULL, 22),
('Indépendance de Djibouti', 'independance-djibouti-DJ', '01977-06-27', '01977-06-27', 'Djibouti devient indépendant de la France et Hassan Gouled Aptidon devient le premier président de la République.', NULL, 11),
('Adhésion de Djibouti à l’ONU', 'adhesion-djibouti-onu-DJ', '01977-09-20', '01977-09-20', 'Djibouti devient membre de l’Organisation des Nations unies quelques mois après son indépendance.', NULL, 22);


-- EGYPTE --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Conquête romaine de l’Égypte', 'conquete-romaine-egypte-EG', '00030-01-01', '00030-08-01', 'L’Égypte devient une province romaine après la défaite de Cléopâtre et Marc Antoine.', NULL, 12),
('Révolte des Boucoloi', 'revolte-boucoloi-egypte-EG', '00172-01-01', '00175-12-31', 'Une grande révolte éclate dans le delta du Nil contre Rome.', NULL, 9),
('Diffusion du christianisme en Égypte', 'diffusion-christianisme-egypte-EG', '00200-01-01', '00300-12-31', 'Le christianisme se diffuse dans les communautés égyptiennes.', NULL, 23),
('Développement du monachisme égyptien', 'developpement-monachisme-egypte-EG', '00320-01-01', '00400-12-31', 'Le monachisme chrétien se développe dans les déserts d’Égypte.', NULL, 23),
('Conquête arabe de l’Égypte', 'conquete-arabe-egypte-EG', '00639-12-01', '00642-09-01', 'Les armées arabes conquièrent l’Égypte aux dépens de Byzance.', NULL, 12),
('Fondation de Fostat', 'fondation-fostat-EG', '00641-01-01', '00641-12-31', 'Amr ibn al-As fonde Fostat, premier grand centre arabe d’Égypte.', NULL, 16),
('Construction de la mosquée d’Amr ibn al-As', 'construction-mosquee-amr-ibn-al-as-EG', '00642-01-01', '00642-12-31', 'La première grande mosquée de Fostat est construite.', NULL, 23),
('Révolte copte de 725', 'revolte-copte-725-EG', '00725-01-01', '00725-12-31', 'Une révolte copte éclate contre l’administration omeyyade.', NULL, 9),
('Fondation de la dynastie tulunide', 'fondation-dynastie-tulunide-EG', '00868-01-01', '00868-12-31', 'Ahmad ibn Tulun établit un pouvoir autonome en Égypte.', NULL, 16),
('Construction de la mosquée Ibn Tulun', 'construction-mosquee-ibn-tulun-EG', '00876-01-01', '00879-12-31', 'La mosquée Ibn Tulun est construite au Caire.', NULL, 23),
('Conquête fatimide de l’Égypte', 'conquete-fatimide-egypte-EG', '00969-01-01', '00969-08-01', 'Les Fatimides conquièrent l’Égypte.', NULL, 12),
('Fondation du Caire', 'fondation-caire-EG', '00969-01-01', '00969-12-31', 'Les Fatimides fondent al-Qahira, future ville du Caire.', NULL, 16),
('Fondation d’Al-Azhar', 'fondation-al-azhar-EG', '00970-01-01', '00972-01-01', 'La mosquée Al-Azhar est fondée au Caire.', NULL, 23),
('Fin de la dynastie fatimide', 'fin-dynastie-fatimide-egypte-EG', '01171-09-10', '01171-09-10', 'Saladin met fin au pouvoir fatimide en Égypte.', NULL, 22),
('Fondation de la dynastie ayyoubide', 'fondation-dynastie-ayyoubide-egypte-EG', '01171-09-10', '01171-09-10', 'Saladin établit la dynastie ayyoubide en Égypte.', NULL, 16),
('Construction de la citadelle du Caire', 'construction-citadelle-caire-EG', '01176-01-01', '01183-12-31', 'Saladin fait construire la citadelle du Caire.', NULL, 17),
('Conquête mamelouke de l’Égypte', 'conquete-mamelouke-egypte-EG', '01250-01-01', '01250-12-31', 'Les Mamelouks prennent le pouvoir en Égypte.', NULL, 12),
('Bataille d’Aïn Djalout', 'bataille-ain-djalout-EG', '01260-09-03', '01260-09-03', 'Les Mamelouks battent les Mongols à Aïn Djalout.', NULL, 7),
('Peste noire en Égypte', 'peste-noire-egypte-EG', '01348-01-01', '01349-12-31', 'La peste noire provoque une grave crise démographique en Égypte.', NULL, 21),
('Construction de la mosquée du sultan Hassan', 'construction-mosquee-sultan-hassan-EG', '01356-01-01', '01363-12-31', 'La mosquée du sultan Hassan est construite au Caire.', NULL, 17),
('Conquête ottomane de l’Égypte', 'conquete-ottomane-egypte-EG', '01517-01-01', '01517-02-01', 'Les Ottomans renversent le pouvoir mamelouk.', NULL, 12),
('Expédition française en Égypte', 'expedition-francaise-egypte-EG', '01798-07-01', '01801-09-01', 'Napoléon mène une expédition militaire française en Égypte.', NULL, 13),
('Bataille des Pyramides', 'bataille-pyramides-EG', '01798-07-21', '01798-07-21', 'Les Français battent les Mamelouks près du Caire.', NULL, 7),
('Bataille du Nil', 'bataille-nil-EG', '01798-08-01', '01798-08-02', 'La flotte française est vaincue par la flotte britannique.', NULL, 7),
('Découverte de la pierre de Rosette', 'decouverte-pierre-rosette-EG', '01799-07-15', '01799-07-15', 'La pierre de Rosette est découverte par les troupes françaises.', NULL, 18),
('Prise de pouvoir de Méhémet Ali', 'prise-pouvoir-mehemet-ali-EG', '01805-05-17', '01805-05-17', 'Méhémet Ali devient gouverneur d’Égypte.', NULL, 22),
('Massacre des Mamelouks au Caire', 'massacre-mamelouks-caire-EG', '01811-03-01', '01811-03-01', 'Méhémet Ali élimine une grande partie des dirigeants mamelouks.', NULL, 10),
('Modernisation de l’armée égyptienne', 'modernisation-armee-egyptienne-EG', '01810-01-01', '01830-12-31', 'Méhémet Ali modernise l’armée et l’administration égyptiennes.', NULL, 17),
('Construction du canal Mahmoudiyah', 'construction-canal-mahmoudiyah-EG', '01818-01-01', '01820-12-31', 'Le canal Mahmoudiyah relie Alexandrie au Nil.', NULL, 19),
('Début de la construction du canal de Suez', 'debut-construction-canal-suez-EG', '01859-04-25', '01859-04-25', 'Les travaux du canal de Suez commencent.', NULL, 19),
('Ouverture du canal de Suez', 'ouverture-canal-suez-EG', '01869-11-17', '01869-11-17', 'Le canal de Suez est officiellement inauguré.', NULL, 17),
('Création du mouvement nationaliste égyptien', 'creation-mouvement-nationaliste-egyptien-EG', '01879-01-01', '01879-12-31', 'Les mouvements nationalistes égyptiens se développent.', NULL, 17),
('Révolte d’Urabi', 'revolte-urabi-EG', '01881-09-01', '01882-09-01', 'Ahmed Urabi dirige une révolte contre le pouvoir et l’influence étrangère.', NULL, 9),
('Occupation britannique de l’Égypte', 'occupation-britannique-egypte-EG', '01882-09-13', '01922-02-28', 'La Grande-Bretagne établit une occupation durable en Égypte.', NULL, 13),
('Création du Musée égyptien du Caire', 'creation-musee-egyptien-caire-EG', '01902-12-15', '01902-12-15', 'Le Musée égyptien du Caire ouvre ses portes.', NULL, 17),
('Création du Wafd', 'creation-wafd-EG', '01918-01-01', '01918-12-31', 'Saad Zaghloul organise le mouvement nationaliste Wafd.', NULL, 17),
('Révolution égyptienne de 1919', 'revolution-egyptienne-1919-EG', '01919-03-01', '01919-12-31', 'Une vaste mobilisation réclame l’indépendance de l’Égypte.', NULL, 8),
('Indépendance nominale de l’Égypte', 'independance-nominale-egypte-EG', '01922-02-28', '01922-02-28', 'Le Royaume-Uni reconnaît l’indépendance de l’Égypte.', NULL, 11),
('Proclamation du Royaume d’Égypte', 'proclamation-royaume-egypte-EG', '01922-03-15', '01922-03-15', 'Fouad Ier devient roi d’Égypte.', NULL, 22),
('Traité anglo-égyptien', 'traite-anglo-egyptien-EG', '01936-08-26', '01936-08-26', 'Un traité modifie les relations entre l’Égypte et le Royaume-Uni.', NULL, 14),
('Révolution égyptienne de 1952', 'revolution-egyptienne-1952-EG', '01952-07-23', '01952-07-23', 'Les Officiers libres renversent la monarchie.', NULL, 8),
('Abolition de la monarchie égyptienne', 'abolition-monarchie-egypte-EG', '01953-06-18', '01953-06-18', 'La monarchie est abolie et la République est proclamée.', NULL, 22),
('Nationalisation du canal de Suez', 'nationalisation-canal-suez-EG', '01956-07-26', '01956-07-26', 'Gamal Abdel Nasser nationalise la compagnie du canal de Suez.', NULL, 25),
('Crise de Suez', 'crise-suez-EG', '01956-10-29', '01956-11-07', 'Une intervention militaire internationale suit la nationalisation du canal.', NULL, 6),
('Création de la République arabe unie', 'creation-republique-arabe-unie-EG', '01958-02-01', '01958-02-01', 'L’Égypte et la Syrie forment la République arabe unie.', NULL, 17),
('Construction du haut barrage d’Assouan', 'construction-haut-barrage-assouan-EG', '01960-01-01', '01970-01-15', 'Le haut barrage d’Assouan est construit sur le Nil afin de réguler les crues, produire de l’électricité et soutenir l’agriculture égyptienne.', NULL, 19),
('Guerre des Six Jours', 'guerre-six-jours-EG', '01967-06-05', '01967-06-10', 'L’Égypte affronte Israël lors de la guerre des Six Jours.', NULL, 6),
('Guerre du Kippour', 'guerre-kippour-EG', '01973-10-06', '01973-10-25', 'L’Égypte attaque les positions israéliennes dans le Sinaï.', NULL, 6),
('Assassinat d’Anouar el-Sadate', 'assassinat-anouar-el-sadate-EG', '01981-10-06', '01981-10-06', 'Le président Anouar el-Sadate est assassiné au Caire.', NULL, 2),
('Révolution égyptienne de 2011', 'revolution-egyptienne-2011-EG', '02011-01-25', '02011-02-11', 'Des manifestations conduisent au départ du président Hosni Moubarak.', NULL, 8);


-- ERYTHREE --

INSERT INTO events (title, slug, date_start, date_end, description, image_url, type_id) VALUES
('Développement des royaumes de la côte érythréenne', 'developpement-royaumes-cote-erythreenne-ER', '01000-01-01', '01500-12-31', 'Des royaumes et chefferies se développent le long de la côte de la mer Rouge et dans les hauts plateaux de l’actuelle Érythrée.', NULL, 16),
('Développement du commerce de la mer Rouge', 'developpement-commerce-mer-rouge-ER', '01000-01-01', '01700-12-31', 'La région participe aux échanges maritimes reliant l’Afrique orientale, l’Arabie et l’Égypte.', NULL, 25),
('Diffusion de l’islam en Érythrée', 'diffusion-islam-erythree-ER', '01200-01-01', '01500-12-31', 'L’islam se diffuse progressivement dans les régions côtières et septentrionales de l’actuelle Érythrée.', NULL, 23),
('Développement du sultanat d’Adal', 'developpement-sultanat-adal-ER', '01400-01-01', '01600-12-31', 'Le sultanat d’Adal étend son influence sur la Corne de l’Afrique et les routes commerciales de la mer Rouge.', NULL, 16),
('Développement du port de Massawa', 'developpement-port-massawa-ER', '01400-01-01', '01800-12-31', 'Massawa devient progressivement un important port commercial de la mer Rouge.', NULL, 25),
('Arrivée des Portugais sur la côte érythréenne', 'arrivee-portugais-cote-erythree-ER', '01540-01-01', '01540-12-31', 'Les Portugais interviennent dans la région de la mer Rouge dans le contexte des rivalités avec les puissances musulmanes.', NULL, 13),
('Conflits entre l’Éthiopie et le sultanat d’Adal', 'conflits-ethiopie-sultanat-adal-ER', '01523-01-01', '01543-12-31', 'Les forces éthiopiennes et le sultanat d’Adal s’affrontent dans plusieurs campagnes militaires qui touchent les régions de l’actuelle Érythrée.', NULL, 6),
('Développement du pouvoir ottoman à Massawa', 'developpement-pouvoir-ottoman-massawa-ER', '01550-01-01', '01600-12-31', 'Les Ottomans établissent leur influence sur Massawa et une partie de la côte de la mer Rouge.', NULL, 13),
('Création de la province ottomane de Habesh', 'creation-province-ottomane-habesh-ER', '01550-01-01', '01550-12-31', 'L’Empire ottoman organise son administration sur la côte de la mer Rouge autour de Massawa et Suakin.', NULL, 17),
('Développement du royaume du Hamasien', 'developpement-royaume-hamasien-ER', '01700-01-01', '01800-12-31', 'Le Hamasien devient une importante entité politique des hauts plateaux érythréens.', NULL, 16),
('Conquête égyptienne de Massawa', 'conquete-egyptienne-massawa-ER', '01860-01-01', '01865-12-31', 'L’Égypte étend son contrôle à Massawa et cherche à consolider sa présence sur la côte érythréenne.', NULL, 12),
('Occupation italienne de Massawa', 'occupation-italienne-massawa-ER', '01885-02-05', '01885-02-05', 'L’Italie prend le contrôle de Massawa et établit une présence coloniale durable en Érythrée.', NULL, 13),
('Création de la colonie italienne d’Érythrée', 'creation-colonie-italienne-erythree-ER', '01890-01-01', '01890-12-31', 'L’Italie organise officiellement ses possessions de la région sous le nom de colonie d’Érythrée.', NULL, 17),
('Fondation d’Asmara comme capitale coloniale', 'fondation-asmara-capitale-ER', '01897-01-01', '01897-12-31', 'Asmara devient le principal centre administratif de la colonie italienne d’Érythrée.', NULL, 16),
('Invasion britannique de l’Érythrée', 'invasion-britannique-erythree-ER', '01941-01-01', '01941-04-01', 'Les forces britanniques conquièrent l’Érythrée aux dépens de l’Italie pendant la Seconde Guerre mondiale.', NULL, 13),
('Fédération de l’Érythrée avec l’Éthiopie', 'federation-erythree-ethiopie-ER', '01952-09-11', '01952-09-11', 'L’Érythrée devient une entité fédérée au sein de l’Empire éthiopien sous supervision internationale.', NULL, 14),
('Abolition de la fédération érythréenne', 'abolition-federation-erythree-ER', '01962-11-14', '01962-11-14', 'L’Éthiopie abolit la fédération et annexe officiellement l’Érythrée.', NULL, 22),
('Début de la guerre d’indépendance érythréenne', 'debut-guerre-independance-erythree-ER', '01961-09-01', '01991-05-24', 'Les mouvements indépendantistes érythréens commencent une lutte armée contre le pouvoir éthiopien.', NULL, 6),
('Indépendance de l’Érythrée', 'independance-erythree-ER', '01993-05-24', '01993-05-24', 'L’Érythrée proclame officiellement son indépendance après un référendum largement favorable à la séparation de l’Éthiopie.', NULL, 11),
('Guerre Érythrée-Éthiopie', 'guerre-erythree-ethiopie-ER', '01998-05-06', '02000-06-18', 'Un conflit armé oppose l’Érythrée et l’Éthiopie principalement autour de différends territoriaux.', NULL, 6);


--