INSERT INTO country (name, code) VALUES
    ('Albanie', 'AL'),
    ('Allemagne', 'DE'),
    ('Andorre', 'AD'),
    ('Autriche', 'AT'),
    ('Belgique', 'BE'),
    ('Biélorussie', 'BY'),
    ('Bosnie-Herzégovine', 'BA'),
    ('Bulgarie', 'BG'),
    ('Chypre', 'CY'),
    ('Croatie', 'HR'),
    ('Danemark', 'DK'),
    ('Espagne', 'ES'),
    ('Estonie', 'EE'),
    ('Finlande', 'FI'),
    ('France', 'FR'),
    ('Grèce', 'GR'),
    ('Hongrie', 'HU'),
    ('Irlande', 'IE'),
    ('Islande', 'IS'),
    ('Italie', 'IT'),
    ('Kosovo', 'XK'),
    ('Lettonie', 'LV'),
    ('Liechtenstein', 'LI'),
    ('Lituanie', 'LT'),
    ('Luxembourg', 'LU'),
    ('Macédoine du Nord', 'MK'),
    ('Malte', 'MT'),
    ('Moldavie', 'MD'),
    ('Monaco', 'MC'),
    ('Monténégro', 'ME'),
    ('Norvège', 'NO'),
    ('Pays-Bas', 'NL'),
    ('Pologne', 'PL'),
    ('Portugal', 'PT'),
    ('République tchèque', 'CZ'),
    ('Roumanie', 'RO'),
    ('Royaume-Uni', 'GB'),
    ('Saint-Marin', 'SM'),
    ('Serbie', 'RS'),
    ('Slovaquie', 'SK'),
    ('Slovénie', 'SI'),
    ('Suède', 'SE'),
    ('Suisse', 'CH'),
    ('Ukraine', 'UA'),
    ('Vatican', 'VA');

