INSERT INTO country (name, code) VALUES
    ('Afrique du Sud', 'ZA'),
    ('Algérie', 'DZ'),
    ('Angola', 'AO'),
    ('Bénin', 'BJ'),
    ('Botswana', 'BW'),
    ('Burkina Faso', 'BF'),
    ('Burundi', 'BI'),
    ('Cameroun', 'CM'),
    ('Cap-Vert', 'CV'),
    ('Comores', 'KM'),
    ('Congo', 'CG'),
    ('Côte d''Ivoire', 'CI'),
    ('Djibouti', 'DJ'),
    ('Égypte', 'EG'),
    ('Érythrée', 'ER'),
    ('Eswatini', 'SZ'),
    ('Éthiopie', 'ET'),
    ('Gabon', 'GA'),
    ('Gambie', 'GM'),
    ('Ghana', 'GH'),
    ('Guinée', 'GN'),
    ('Guinée-Bissau', 'GW'),
    ('Guinée équatoriale', 'GQ'),
    ('Kenya', 'KE'),
    ('Lesotho', 'LS'),
    ('Liberia', 'LR'),
    ('Libye', 'LY'),
    ('Madagascar', 'MG'),
    ('Malawi', 'MW'),
    ('Mali', 'ML'),
    ('Maroc', 'MA'),
    ('Maurice', 'MU'),
    ('Mauritanie', 'MR'),
    ('Mozambique', 'MZ'),
    ('Namibie', 'NA'),
    ('Niger', 'NE'),
    ('Nigeria', 'NG'),
    ('Ouganda', 'UG'),
    ('République centrafricaine', 'CF'),
    ('République démocratique du Congo', 'CD'),
    ('Rwanda', 'RW'),
    ('Sahara occidental', 'EH'),
    ('Sao Tomé-et-Principe', 'ST'),
    ('Sénégal', 'SN'),
    ('Seychelles', 'SC'),
    ('Sierra Leone', 'SL'),
    ('Somalie', 'SO'),
    ('Soudan', 'SD'),
    ('Soudan du Sud', 'SS'),
    ('Tanzanie', 'TZ'),
    ('Tchad', 'TD'),
    ('Togo', 'TG'),
    ('Tunisie', 'TN'),
    ('Zambie', 'ZM'),
    ('Zimbabwe', 'ZW');
