INSERT INTO country (name, code) VALUES
    ('Afghanistan', 'AF'),
    ('Arabie saoudite', 'SA'),
    ('Arménie', 'AM'),
    ('Azerbaïdjan', 'AZ'),
    ('Bahreïn', 'BH'),
    ('Bangladesh', 'BD'),
    ('Bhoutan', 'BT'),
    ('Brunei', 'BN'),
    ('Cambodge', 'KH'),
    ('Chine', 'CN'),
    ('Corée du Nord', 'KP'),
    ('Corée du Sud', 'KR'),
    ('Émirats arabes unis', 'AE'),
    ('Géorgie', 'GE'),
    ('Inde', 'IN'),
    ('Indonésie', 'ID'),
    ('Irak', 'IQ'),
    ('Iran', 'IR'),
    ('Israël', 'IL'),
    ('Japon', 'JP'),
    ('Jordanie', 'JO'),
    ('Kazakhstan', 'KZ'),
    ('Kirghizistan', 'KG'),
    ('Koweït', 'KW'),
    ('Laos', 'LA'),
    ('Liban', 'LB'),
    ('Malaisie', 'MY'),
    ('Maldives', 'MV'),
    ('Mongolie', 'MN'),
    ('Myanmar', 'MM'),
    ('Népal', 'NP'),
    ('Oman', 'OM'),
    ('Ouzbékistan', 'UZ'),
    ('Pakistan', 'PK'),
    ('Palestine', 'PS'),
    ('Philippines', 'PH'),
    ('Qatar', 'QA'),
    ('Russie', 'RU'),
    ('Singapour', 'SG'),
    ('Sri Lanka', 'LK'),
    ('Syrie', 'SY'),
    ('Tadjikistan', 'TJ'),
    ('Taïwan', 'TW'),
    ('Thaïlande', 'TH'),
    ('Timor oriental', 'TL'),
    ('Turkménistan', 'TM'),
    ('Turquie', 'TR'),
    ('Vietnam', 'VN'),
    ('Yémen', 'YE');
